export const wasmMaterials = [
  "acid",
  "alcohol",
  "blood",
  "blood_fungi",
  "blood_worm",
  "cement",
  "lava",
  "magic_liquid_berserk",
  "magic_liquid_charm",
  "magic_liquid_faster_levitation",
  "magic_liquid_faster_levitation_and_movement",
  "magic_liquid_invisibility",
  "magic_liquid_mana_regeneration",
  "magic_liquid_movement_faster",
  "magic_liquid_protection_all",
  "magic_liquid_teleportation",
  "magic_liquid_unstable_polymorph",
  "magic_liquid_unstable_teleportation",
  "magic_liquid_worm_attractor",
  "material_confusion",
  "mud",
  "oil",
  "poison",
  "radioactive_liquid",
  "swamp",
  "urine",
  "water",
  "water_ice",
  "water_swamp",
  "magic_liquid_random_polymorph",
  "bone",
  "brass",
  "coal",
  "copper",
  "diamond",
  "fungi",
  "gold",
  "grass",
  "gunpowder",
  "gunpowder_explosive",
  "rotten_meat",
  "sand",
  "silver",
  "slime",
  "snow",
  "soil",
  "wax",
  "honey",
  "water_static",
  "water_salt",
  "material_darkness",
  "peat",
  "fungisoil",
  "blood_cold",
  "acid_gas",
  "acid_gas_static",
  "poison_gas",
  "fungal_gas",
  "radioactive_gas",
  "radioactive_gas_static",
  "magic_liquid_polymorph",
  "steam",
  "smoke",
  "snow_sticky",
  "rock_static",
  "gold_box2d",
  "sima",
  "vomit",
  "pea_soup",
  "rock_static_radioactive",
  "mimic_liquid",
  "poo",
  "void_liquid",
  "cheese_static",
  "grass_holy",
  "mammi",
  "rotten_meat_radioactive",
] as const;

export const materialName = (id: number) => wasmMaterials[id] ?? "";

const fungalFromGroups = [
  ["water", "water_static", "water_salt", "water_ice"],
  ["lava"],
  ["radioactive_liquid", "poison", "material_darkness"],
  ["oil", "swamp", "peat"],
  ["blood"],
  ["blood_fungi", "fungi", "fungisoil"],
  ["blood_cold", "blood_worm"],
  ["acid"],
  ["acid_gas", "acid_gas_static", "poison_gas", "fungal_gas", "radioactive_gas", "radioactive_gas_static"],
  ["magic_liquid_polymorph", "magic_liquid_unstable_polymorph"],
  ["magic_liquid_berserk", "magic_liquid_charm", "magic_liquid_invisibility"],
  ["diamond"],
  ["silver", "brass", "copper"],
  ["steam", "smoke"],
  ["sand"],
  ["snow_sticky"],
  ["rock_static"],
  ["gold", "gold_box2d"],
] as const;

export const fungalFromMaterials = (group: number, to: string) =>
  fungalFromGroups[group]?.filter(material => material !== to) ?? [];
