/* eslint-disable */
/* tslint:disable */

var create_Alchemy = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(create_Alchemy = {})  {

var e;e||(e=typeof create_Alchemy !== 'undefined' ? create_Alchemy : {});var aa,t;e.ready=new Promise(function(a,b){aa=a;t=b});var ba=Object.assign({},e),ca="object"==typeof window,u="function"==typeof importScripts,da="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,v="",w,y;
if(da){var fs=require("fs"),ea=require("path");v=u?ea.dirname(v)+"/":__dirname+"/";w=(a,b)=>{a=a.startsWith("file://")?new URL(a):ea.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};y=a=>{a=w(a,!0);a.buffer||(a=new Uint8Array(a));return a};process.argv.slice(2);e.inspect=function(){return"[Emscripten Module object]"}}else if(ca||u)u?v=self.location.href:"undefined"!=typeof document&&document.currentScript&&(v=document.currentScript.src),_scriptDir&&(v=_scriptDir),0!==v.indexOf("blob:")?v=v.substr(0,
v.replace(/[?#].*/,"").lastIndexOf("/")+1):v="",w=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(y=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});e.print||console.log.bind(console);var A=e.printErr||console.warn.bind(console);Object.assign(e,ba);ba=null;var B;e.wasmBinary&&(B=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!=typeof WebAssembly&&C("no native wasm support detected");
var D,fa=!1,ha="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,E,G,H,I,J,L,ia,ja;function ka(){var a=D.buffer;e.HEAP8=E=new Int8Array(a);e.HEAP16=H=new Int16Array(a);e.HEAP32=J=new Int32Array(a);e.HEAPU8=G=new Uint8Array(a);e.HEAPU16=I=new Uint16Array(a);e.HEAPU32=L=new Uint32Array(a);e.HEAPF32=ia=new Float32Array(a);e.HEAPF64=ja=new Float64Array(a)}var la,ma=[],na=[],oa=[];function pa(){var a=e.preRun.shift();ma.unshift(a)}var M=0,qa=null,N=null;
function C(a){if(e.onAbort)e.onAbort(a);a="Aborted("+a+")";A(a);fa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");t(a);throw a;}function ra(a){return a.startsWith("data:application/octet-stream;base64,")}var O;O="Alchemy.wasm";if(!ra(O)){var sa=O;O=e.locateFile?e.locateFile(sa,v):v+sa}function ta(a){try{if(a==O&&B)return new Uint8Array(B);if(y)return y(a);throw"both async and sync fetching of the wasm failed";}catch(b){C(b)}}
function ua(a){return B||!ca&&!u||"function"!=typeof fetch?Promise.resolve().then(function(){return ta(a)}):fetch(a,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(function(){return ta(a)})}function va(a,b,c){return ua(a).then(function(d){return WebAssembly.instantiate(d,b)}).then(function(d){return d}).then(c,function(d){A("failed to asynchronously prepare wasm: "+d);C(d)})}
function wa(a,b){var c=O;return B||"function"!=typeof WebAssembly.instantiateStreaming||ra(c)||da||"function"!=typeof fetch?va(c,a,b):fetch(c,{credentials:"same-origin"}).then(function(d){return WebAssembly.instantiateStreaming(d,a).then(b,function(f){A("wasm streaming compile failed: "+f);A("falling back to ArrayBuffer instantiation");return va(c,a,b)})})}function xa(a){for(;0<a.length;)a.shift()(e)}
function ya(a){this.B=a-24;this.J=function(b){L[this.B+4>>2]=b};this.G=function(b){L[this.B+8>>2]=b};this.H=function(){J[this.B>>2]=0};this.F=function(){E[this.B+12>>0]=0};this.I=function(){E[this.B+13>>0]=0};this.C=function(b,c){this.D();this.J(b);this.G(c);this.H();this.F();this.I()};this.D=function(){L[this.B+16>>2]=0}}var za=0;function Aa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ba=void 0;
function P(a){for(var b="";G[a];)b+=Ba[G[a++]];return b}var Q={},R={},S={};function Ca(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Da(a,b){a=Ca(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}
function Ea(a){var b=Error,c=Da(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Fa=void 0;function T(a){throw new Fa(a);}var Ga=void 0;
function Ha(a,b){function c(k){k=b(k);if(k.length!==d.length)throw new Ga("Mismatched type converter count");for(var l=0;l<d.length;++l)U(d[l],k[l])}var d=[];d.forEach(function(k){S[k]=a});var f=Array(a.length),h=[],g=0;a.forEach((k,l)=>{R.hasOwnProperty(k)?f[l]=R[k]:(h.push(k),Q.hasOwnProperty(k)||(Q[k]=[]),Q[k].push(()=>{f[l]=R[k];++g;g===h.length&&c(f)}))});0===h.length&&c(f)}
function U(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||T('type "'+d+'" must have a positive integer typeid pointer');if(R.hasOwnProperty(a)){if(c.L)return;T("Cannot register type '"+d+"' twice")}R[a]=b;delete S[a];Q.hasOwnProperty(a)&&(b=Q[a],delete Q[a],b.forEach(f=>f()))}
var Ia=[],V=[{},{value:void 0},{value:null},{value:!0},{value:!1}],Ja=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ia.length?Ia.pop():V.length;V[b]={M:1,value:a};return b}};function Ma(a){return this.fromWireType(J[a>>2])}function Na(a,b){switch(b){case 2:return function(c){return this.fromWireType(ia[c>>2])};case 3:return function(c){return this.fromWireType(ja[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Oa(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Da(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}function Pa(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function Qa(a,b){var c=e;if(void 0===c[a].v){var d=c[a];c[a]=function(){c[a].v.hasOwnProperty(arguments.length)||T("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].v+")!");return c[a].v[arguments.length].apply(this,arguments)};c[a].v=[];c[a].v[d.K]=d}}
function Ra(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].v&&void 0!==e[a].v[c])&&T("Cannot register public name '"+a+"' twice"),Qa(a,a),e.hasOwnProperty(c)&&T("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].v[c]=b):(e[a]=b,void 0!==c&&(e[a].O=c))}function Sa(a,b){for(var c=[],d=0;d<a;d++)c.push(L[b+4*d>>2]);return c}var W=[];function Ta(a){var b=W[a];b||(a>=W.length&&(W.length=a+1),W[a]=b=la.get(a));return b}
function Ua(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=e["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=Ta(b).apply(null,c);return d}}function Va(a,b){a=P(a);var c=a.includes("j")?Ua(a,b):Ta(b);"function"!=typeof c&&T("unknown function pointer with signature "+a+": "+b);return c}var Wa=void 0;function Xa(a){a=Ya(a);var b=P(a);X(a);return b}
function Za(a,b){function c(h){f[h]||R[h]||(S[h]?S[h].forEach(c):(d.push(h),f[h]=!0))}var d=[],f={};b.forEach(c);throw new Wa(a+": "+d.map(Xa).join([", "]));}function $a(a,b,c){switch(b){case 0:return c?function(d){return E[d]}:function(d){return G[d]};case 1:return c?function(d){return H[d>>1]}:function(d){return I[d>>1]};case 2:return c?function(d){return J[d>>2]}:function(d){return L[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}
var ab="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function bb(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&I[c];)++c;c<<=1;if(32<c-a&&ab)return ab.decode(G.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var f=H[a+2*d>>1];if(0==f)break;c+=String.fromCharCode(f)}return c}function cb(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)H[b>>1]=a.charCodeAt(f),b+=2;H[b>>1]=0;return b-d}function db(a){return 2*a.length}
function eb(a,b){for(var c=0,d="";!(c>=b/4);){var f=J[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}function fb(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var g=a.charCodeAt(++f);h=65536+((h&1023)<<10)|g&1023}J[b>>2]=h;b+=4;if(b+4>c)break}J[b>>2]=0;return b-d}
function gb(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}for(var hb=Array(256),Y=0;256>Y;++Y)hb[Y]=String.fromCharCode(Y);Ba=hb;Fa=e.BindingError=Ea("BindingError");Ga=e.InternalError=Ea("InternalError");e.count_emval_handles=function(){for(var a=0,b=5;b<V.length;++b)void 0!==V[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<V.length;++a)if(void 0!==V[a])return V[a];return null};Wa=e.UnboundTypeError=Ea("UnboundTypeError");
var jb={g:function(a,b,c){(new ya(a)).C(b,c);za++;throw a;},k:function(){},i:function(a,b,c,d,f){var h=Aa(c);b=P(b);U(a,{name:b,fromWireType:function(g){return!!g},toWireType:function(g,k){return k?d:f},argPackAdvance:8,readValueFromPointer:function(g){if(1===c)var k=E;else if(2===c)k=H;else if(4===c)k=J;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[g>>h])},A:null})},h:function(a,b){b=P(b);U(a,{name:b,fromWireType:function(c){c||T("Cannot use deleted val. handle = "+
c);var d=V[c].value;4<c&&0===--V[c].M&&(V[c]=void 0,Ia.push(c));return d},toWireType:function(c,d){return Ja(d)},argPackAdvance:8,readValueFromPointer:Ma,A:null})},e:function(a,b,c){c=Aa(c);b=P(b);U(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){return f},argPackAdvance:8,readValueFromPointer:Na(b,c),A:null})},f:function(a,b,c,d,f,h,g){var k=Sa(b,c);a=P(a);f=Va(d,f);Ra(a,function(){Za("Cannot call "+a+" due to unbound types",k)},b-1);Ha(k,function(l){var m=[l[0],null].concat(l.slice(1)),
p=l=a,r=f,q=m.length;2>q&&T("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var x=null!==m[1]&&!1,z=!1,n=1;n<m.length;++n)if(null!==m[n]&&void 0===m[n].A){z=!0;break}var Ka="void"!==m[0].name,F="",K="";for(n=0;n<q-2;++n)F+=(0!==n?", ":"")+"arg"+n,K+=(0!==n?", ":"")+"arg"+n+"Wired";p="return function "+Ca(p)+"("+F+") {\nif (arguments.length !== "+(q-2)+") {\nthrowBindingError('function "+p+" called with ' + arguments.length + ' arguments, expected "+(q-2)+" args!');\n}\n";
z&&(p+="var destructors = [];\n");var La=z?"destructors":"null";F="throwBindingError invoker fn runDestructors retType classParam".split(" ");r=[T,r,h,Pa,m[0],m[1]];x&&(p+="var thisWired = classParam.toWireType("+La+", this);\n");for(n=0;n<q-2;++n)p+="var arg"+n+"Wired = argType"+n+".toWireType("+La+", arg"+n+"); // "+m[n+2].name+"\n",F.push("argType"+n),r.push(m[n+2]);x&&(K="thisWired"+(0<K.length?", ":"")+K);p+=(Ka||g?"var rv = ":"")+"invoker(fn"+(0<K.length?", ":"")+K+");\n";if(z)p+="runDestructors(destructors);\n";
else for(n=x?1:2;n<m.length;++n)q=1===n?"thisWired":"arg"+(n-2)+"Wired",null!==m[n].A&&(p+=q+"_dtor("+q+"); // "+m[n].name+"\n",F.push(q+"_dtor"),r.push(m[n].A));Ka&&(p+="var ret = retType.fromWireType(rv);\nreturn ret;\n");F.push(p+"}\n");m=Oa(F).apply(null,r);n=b-1;if(!e.hasOwnProperty(l))throw new Ga("Replacing nonexistant public symbol");void 0!==e[l].v&&void 0!==n?e[l].v[n]=m:(e[l]=m,e[l].K=n);return[]})},b:function(a,b,c,d,f){b=P(b);-1===f&&(f=4294967295);f=Aa(c);var h=k=>k;if(0===d){var g=
32-8*c;h=k=>k<<g>>>g}c=b.includes("unsigned")?function(k,l){return l>>>0}:function(k,l){return l};U(a,{name:b,fromWireType:h,toWireType:c,argPackAdvance:8,readValueFromPointer:$a(b,f,0!==d),A:null})},a:function(a,b,c){function d(h){h>>=2;var g=L;return new f(g.buffer,g[h+1],g[h])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=P(c);U(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{L:!0})},d:function(a,b){b=P(b);var c="std::string"===
b;U(a,{name:b,fromWireType:function(d){var f=L[d>>2],h=d+4;if(c)for(var g=h,k=0;k<=f;++k){var l=h+k;if(k==f||0==G[l]){if(g){var m=g;var p=G,r=m+(l-g);for(g=m;p[g]&&!(g>=r);)++g;if(16<g-m&&p.buffer&&ha)m=ha.decode(p.subarray(m,g));else{for(r="";m<g;){var q=p[m++];if(q&128){var x=p[m++]&63;if(192==(q&224))r+=String.fromCharCode((q&31)<<6|x);else{var z=p[m++]&63;q=224==(q&240)?(q&15)<<12|x<<6|z:(q&7)<<18|x<<12|z<<6|p[m++]&63;65536>q?r+=String.fromCharCode(q):(q-=65536,r+=String.fromCharCode(55296|q>>
10,56320|q&1023))}}else r+=String.fromCharCode(q)}m=r}}else m="";if(void 0===n)var n=m;else n+=String.fromCharCode(0),n+=m;g=l+1}}else{n=Array(f);for(k=0;k<f;++k)n[k]=String.fromCharCode(G[h+k]);n=n.join("")}X(d);return n},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var h,g="string"==typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||T("Cannot pass non-string to std::string");if(c&&g){var k=0;for(h=0;h<f.length;++h){var l=f.charCodeAt(h);
127>=l?k++:2047>=l?k+=2:55296<=l&&57343>=l?(k+=4,++h):k+=3}h=k}else h=f.length;k=ib(4+h+1);l=k+4;L[k>>2]=h;if(c&&g){if(g=l,l=h+1,h=G,0<l){l=g+l-1;for(var m=0;m<f.length;++m){var p=f.charCodeAt(m);if(55296<=p&&57343>=p){var r=f.charCodeAt(++m);p=65536+((p&1023)<<10)|r&1023}if(127>=p){if(g>=l)break;h[g++]=p}else{if(2047>=p){if(g+1>=l)break;h[g++]=192|p>>6}else{if(65535>=p){if(g+2>=l)break;h[g++]=224|p>>12}else{if(g+3>=l)break;h[g++]=240|p>>18;h[g++]=128|p>>12&63}h[g++]=128|p>>6&63}h[g++]=128|p&63}}h[g]=
0}}else if(g)for(g=0;g<h;++g)m=f.charCodeAt(g),255<m&&(X(l),T("String has UTF-16 code units that do not fit in 8 bits")),G[l+g]=m;else for(g=0;g<h;++g)G[l+g]=f[g];null!==d&&d.push(X,k);return k},argPackAdvance:8,readValueFromPointer:Ma,A:function(d){X(d)}})},c:function(a,b,c){c=P(c);if(2===b){var d=bb;var f=cb;var h=db;var g=()=>I;var k=1}else 4===b&&(d=eb,f=fb,h=gb,g=()=>L,k=2);U(a,{name:c,fromWireType:function(l){for(var m=L[l>>2],p=g(),r,q=l+4,x=0;x<=m;++x){var z=l+4+x*b;if(x==m||0==p[z>>k])q=
d(q,z-q),void 0===r?r=q:(r+=String.fromCharCode(0),r+=q),q=z+b}X(l);return r},toWireType:function(l,m){"string"!=typeof m&&T("Cannot pass non-string to C++ string type "+c);var p=h(m),r=ib(4+p+b);L[r>>2]=p>>k;f(m,r+4,p+b);null!==l&&l.push(X,r);return r},argPackAdvance:8,readValueFromPointer:Ma,A:function(l){X(l)}})},j:function(a,b){b=P(b);U(a,{N:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},l:function(){C("")},n:function(a,b,c){G.copyWithin(a,b,b+c)},m:function(a){var b=
G.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var f=Math,h=f.min;d=Math.max(a,d);d+=(65536-d%65536)%65536;a:{var g=D.buffer;try{D.grow(h.call(f,2147483648,d)-g.byteLength+65535>>>16);ka();var k=1;break a}catch(l){}k=void 0}if(k)return!0}return!1}};
(function(){function a(c){c=c.exports;e.asm=c;D=e.asm.o;ka();la=e.asm.r;na.unshift(e.asm.p);M--;e.monitorRunDependencies&&e.monitorRunDependencies(M);if(0==M&&(null!==qa&&(clearInterval(qa),qa=null),N)){var d=N;N=null;d()}return c}var b={a:jb};M++;e.monitorRunDependencies&&e.monitorRunDependencies(M);if(e.instantiateWasm)try{return e.instantiateWasm(b,a)}catch(c){A("Module.instantiateWasm callback failed with error: "+c),t(c)}wa(b,function(c){a(c.instance)}).catch(t);return{}})();
var ib=e._malloc=function(){return(ib=e._malloc=e.asm.q).apply(null,arguments)},Ya=e.___getTypeName=function(){return(Ya=e.___getTypeName=e.asm.s).apply(null,arguments)};e.__embind_initialize_bindings=function(){return(e.__embind_initialize_bindings=e.asm.t).apply(null,arguments)};var X=e._free=function(){return(X=e._free=e.asm.u).apply(null,arguments)},Z;N=function kb(){Z||lb();Z||(N=kb)};
function lb(){function a(){if(!Z&&(Z=!0,e.calledRun=!0,!fa)){xa(na);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();oa.unshift(b)}xa(oa)}}if(!(0<M)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)pa();xa(ma);0<M||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();lb();


  return create_Alchemy.ready
}

);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = create_Alchemy;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return create_Alchemy; });
else if (typeof exports === 'object')
  exports["create_Alchemy"] = create_Alchemy;
