import { describe, it, expect } from "vitest";
import { FungalShiftInfoProvider } from "./";
import { loadRandom } from "../../../../../testHelpers";

describe("FungalShiftInfoProvider", () => {
  const tests = [
    {
      seed: 123,
      ans: [
        {
          flaskTo: false,
          flaskFrom: true,
          from: ["lava"],
          to: "sand",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: false,
          flaskFrom: true,
          from: ["magic_liquid_polymorph", "magic_liquid_unstable_polymorph"],
          to: "blood",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: false,
          flaskFrom: true,
          from: ["radioactive_liquid", "poison", "material_darkness"],
          to: "water",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: false,
          flaskFrom: true,
          from: ["water", "water_static", "water_salt", "water_ice"],
          to: "radioactive_liquid",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: false,
          flaskFrom: true,
          from: ["lava"],
          to: "blood",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: true,
          flaskFrom: false,
          from: ["radioactive_liquid", "poison", "material_darkness"],
          to: "acid",
          gold_to_x: "mammi",
          grass_to_x: "grass",
        },
        {
          flaskTo: false,
          flaskFrom: true,
          from: ["oil", "swamp", "peat"],
          to: "water",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: false,
          flaskFrom: true,
          from: ["water", "water_static", "water_salt", "water_ice"],
          to: "pea_soup",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: false,
          flaskFrom: true,
          from: ["acid"],
          to: "lava",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: true,
          flaskFrom: false,
          from: ["water", "water_static", "water_salt", "water_ice"],
          to: "blood_fungi",
          gold_to_x: "mammi",
          grass_to_x: "grass",
        },
        {
          flaskTo: true,
          flaskFrom: false,
          from: ["oil", "swamp", "peat"],
          to: "acid",
          gold_to_x: "mammi",
          grass_to_x: "grass",
        },
        {
          flaskTo: true,
          flaskFrom: false,
          from: ["oil", "swamp", "peat"],
          to: "vomit",
          gold_to_x: "acid_gas",
          grass_to_x: "grass",
        },
        {
          flaskTo: false,
          flaskFrom: false,
          from: ["acid"],
          to: "fungi",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: true,
          flaskFrom: false,
          from: [
            "acid_gas",
            "acid_gas_static",
            "poison_gas",
            "fungal_gas",
            "radioactive_gas",
            "radioactive_gas_static",
          ],
          to: "gunpowder",
          gold_to_x: "brass",
          grass_to_x: "grass",
        },
        {
          flaskTo: false,
          flaskFrom: false,
          from: ["silver", "brass", "copper"],
          to: "acid",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: false,
          flaskFrom: false,
          from: ["oil", "swamp", "peat"],
          to: "silver",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: false,
          flaskFrom: true,
          from: ["diamond"],
          to: "silver",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: false,
          flaskFrom: true,
          from: ["diamond"],
          to: "radioactive_liquid",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: true,
          flaskFrom: false,
          from: ["lava"],
          to: "radioactive_liquid",
          gold_to_x: "acid_gas",
          grass_to_x: "grass",
        },
        {
          flaskTo: false,
          flaskFrom: false,
          from: ["lava"],
          to: "water",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
      ],
    },
    {
      seed: 1307857905,
      ans: [
        {
          flaskTo: false,
          flaskFrom: false,
          from: ["oil", "swamp", "peat"],
          to: "steam",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: false,
          flaskFrom: false,
          from: ["diamond"],
          to: "silver",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: false,
          flaskFrom: false,
          from: ["diamond"],
          to: "silver",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: false,
          flaskFrom: true,
          from: ["diamond"],
          to: "mimic_liquid",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: true,
          flaskFrom: false,
          from: ["snow_sticky"],
          to: "poison",
          gold_to_x: "vomit",
          grass_to_x: "grass",
        },
        {
          flaskTo: true,
          flaskFrom: false,
          from: ["blood_cold", "blood_worm"],
          to: "alcohol",
          gold_to_x: "pea_soup",
          grass_to_x: "grass",
        },
        {
          flaskTo: false,
          flaskFrom: false,
          from: ["blood"],
          to: "fungi",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: false,
          flaskFrom: true,
          from: ["acid"],
          to: "sand",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: false,
          flaskFrom: true,
          from: ["magic_liquid_polymorph", "magic_liquid_unstable_polymorph"],
          to: "water",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: false,
          flaskFrom: true,
          from: ["water", "water_static", "water_salt", "water_ice"],
          to: "lava",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: false,
          flaskFrom: true,
          from: ["lava"],
          to: "oil",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: true,
          flaskFrom: false,
          from: ["lava"],
          grass_to_x: "grass",
          to: "water_swamp",
          gold_to_x: "silver",
        },
        {
          flaskTo: false,
          flaskFrom: false,
          from: ["blood"],
          to: "water",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: false,
          flaskFrom: true,
          from: ["water", "water_static", "water_salt", "water_ice"],
          to: "gunpowder",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: true,
          flaskFrom: false,
          from: ["steam", "smoke"],
          to: "blood_fungi",
          grass_to_x: "grass",
          gold_to_x: "radioactive_liquid",
        },
        {
          flaskTo: false,
          flaskFrom: false,
          from: ["oil", "swamp", "peat"],
          to: "blood_fungi",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: false,
          flaskFrom: true,
          from: ["radioactive_liquid", "poison", "material_darkness"],
          to: "steam",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: true,
          flaskFrom: false,
          from: ["diamond"],
          to: "radioactive_liquid",
          grass_to_x: "grass",
          gold_to_x: "radioactive_liquid",
        },
        {
          flaskTo: false,
          flaskFrom: true,
          from: ["lava"],
          to: "radioactive_liquid",
          gold_to_x: "gold",
          grass_to_x: "grass_holy",
        },
        {
          flaskTo: true,
          flaskFrom: false,
          from: ["lava"],
          to: "poison",
          gold_to_x: "radioactive_liquid",
          grass_to_x: "grass",
        },
      ],
    },
  ];

  describe("#provide", () => {
    tests.forEach((t, i) => {
      it(`Should generate correct output #${i}`, async () => {
        const randoms = await loadRandom();
        const ap = new FungalShiftInfoProvider(randoms);
        await ap.ready();
        randoms.SetWorldSeed(t.seed);
        const res = ap.provide();
        expect(res).toEqual(t.ans);
      });
    });
  });
});
