/* eslint-disable */


var create_noita_random = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(create_noita_random) {
  create_noita_random = create_noita_random || {};


var a;a||=typeof create_noita_random !== 'undefined' ? create_noita_random : {};var aa,ba;a.ready=new Promise(function(c,d){aa=c;ba=d});
Object.getOwnPropertyDescriptor(a.ready,"_generate_map")||(Object.defineProperty(a.ready,"_generate_map",{configurable:!0,get:function(){b("You are getting _generate_map on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_generate_map",{configurable:!0,set:function(){b("You are setting _generate_map on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_emscripten_stack_get_end")||(Object.defineProperty(a.ready,"_emscripten_stack_get_end",{configurable:!0,get:function(){b("You are getting _emscripten_stack_get_end on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_emscripten_stack_get_end",{configurable:!0,set:function(){b("You are setting _emscripten_stack_get_end on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_emscripten_stack_get_free")||(Object.defineProperty(a.ready,"_emscripten_stack_get_free",{configurable:!0,get:function(){b("You are getting _emscripten_stack_get_free on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_emscripten_stack_get_free",{configurable:!0,set:function(){b("You are setting _emscripten_stack_get_free on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_emscripten_stack_init")||(Object.defineProperty(a.ready,"_emscripten_stack_init",{configurable:!0,get:function(){b("You are getting _emscripten_stack_init on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_emscripten_stack_init",{configurable:!0,set:function(){b("You are setting _emscripten_stack_init on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_stackSave")||(Object.defineProperty(a.ready,"_stackSave",{configurable:!0,get:function(){b("You are getting _stackSave on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_stackSave",{configurable:!0,set:function(){b("You are setting _stackSave on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_stackRestore")||(Object.defineProperty(a.ready,"_stackRestore",{configurable:!0,get:function(){b("You are getting _stackRestore on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_stackRestore",{configurable:!0,set:function(){b("You are setting _stackRestore on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_stackAlloc")||(Object.defineProperty(a.ready,"_stackAlloc",{configurable:!0,get:function(){b("You are getting _stackAlloc on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_stackAlloc",{configurable:!0,set:function(){b("You are setting _stackAlloc on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"___wasm_call_ctors")||(Object.defineProperty(a.ready,"___wasm_call_ctors",{configurable:!0,get:function(){b("You are getting ___wasm_call_ctors on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"___wasm_call_ctors",{configurable:!0,set:function(){b("You are setting ___wasm_call_ctors on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"___errno_location")||(Object.defineProperty(a.ready,"___errno_location",{configurable:!0,get:function(){b("You are getting ___errno_location on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"___errno_location",{configurable:!0,set:function(){b("You are setting ___errno_location on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_malloc")||(Object.defineProperty(a.ready,"_malloc",{configurable:!0,get:function(){b("You are getting _malloc on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_malloc",{configurable:!0,set:function(){b("You are setting _malloc on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_free")||(Object.defineProperty(a.ready,"_free",{configurable:!0,get:function(){b("You are getting _free on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_free",{configurable:!0,set:function(){b("You are setting _free on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_setThrew")||(Object.defineProperty(a.ready,"_setThrew",{configurable:!0,get:function(){b("You are getting _setThrew on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_setThrew",{configurable:!0,set:function(){b("You are setting _setThrew on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"onRuntimeInitialized")||(Object.defineProperty(a.ready,"onRuntimeInitialized",{configurable:!0,get:function(){b("You are getting onRuntimeInitialized on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"onRuntimeInitialized",{configurable:!0,set:function(){b("You are setting onRuntimeInitialized on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
var m={},u;for(u in a)a.hasOwnProperty(u)&&(m[u]=a[u]);var ca=!1,v=!1;ca="object"===typeof window;v="function"===typeof importScripts;if(a.ENVIRONMENT)throw Error("Module.ENVIRONMENT has been deprecated. To force the environment, use the ENVIRONMENT compile-time option (for example, -s ENVIRONMENT=web or -s ENVIRONMENT=node)");var w="",da;
if(ca||v){v?w=self.location.href:"undefined"!==typeof document&&document.currentScript&&(w=document.currentScript.src);_scriptDir&&(w=_scriptDir);0!==w.indexOf("blob:")?w=w.substr(0,w.lastIndexOf("/")+1):w="";if("object"!==typeof window&&"function"!==typeof importScripts)throw Error("not compiled for this environment (did you build to HTML and try to run it not on the web, or set ENVIRONMENT to something - like node - and run it someplace else - like on the web?)");v&&(da=function(c){var d=new XMLHttpRequest;
d.open("GET",c,!1);d.responseType="arraybuffer";d.send(null);return new Uint8Array(d.response)})}else throw Error("environment detection error");var x=a.printErr||console.warn.bind(console);for(u in m)m.hasOwnProperty(u)&&(a[u]=m[u]);m=null;Object.getOwnPropertyDescriptor(a,"arguments")||Object.defineProperty(a,"arguments",{configurable:!0,get:function(){b("Module.arguments has been replaced with plain arguments_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
Object.getOwnPropertyDescriptor(a,"thisProgram")||Object.defineProperty(a,"thisProgram",{configurable:!0,get:function(){b("Module.thisProgram has been replaced with plain thisProgram (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});Object.getOwnPropertyDescriptor(a,"quit")||Object.defineProperty(a,"quit",{configurable:!0,get:function(){b("Module.quit has been replaced with plain quit_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
y("undefined"===typeof a.memoryInitializerPrefixURL,"Module.memoryInitializerPrefixURL option was removed, use Module.locateFile instead");y("undefined"===typeof a.pthreadMainPrefixURL,"Module.pthreadMainPrefixURL option was removed, use Module.locateFile instead");y("undefined"===typeof a.cdInitializerPrefixURL,"Module.cdInitializerPrefixURL option was removed, use Module.locateFile instead");y("undefined"===typeof a.filePackagePrefixURL,"Module.filePackagePrefixURL option was removed, use Module.locateFile instead");
y("undefined"===typeof a.read,"Module.read option was removed (modify read_ in JS)");y("undefined"===typeof a.readAsync,"Module.readAsync option was removed (modify readAsync in JS)");y("undefined"===typeof a.readBinary,"Module.readBinary option was removed (modify readBinary in JS)");y("undefined"===typeof a.setWindowTitle,"Module.setWindowTitle option was removed (modify setWindowTitle in JS)");y("undefined"===typeof a.TOTAL_MEMORY,"Module.TOTAL_MEMORY has been renamed Module.INITIAL_MEMORY");
Object.getOwnPropertyDescriptor(a,"read")||Object.defineProperty(a,"read",{configurable:!0,get:function(){b("Module.read has been replaced with plain read_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});Object.getOwnPropertyDescriptor(a,"readAsync")||Object.defineProperty(a,"readAsync",{configurable:!0,get:function(){b("Module.readAsync has been replaced with plain readAsync (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
Object.getOwnPropertyDescriptor(a,"readBinary")||Object.defineProperty(a,"readBinary",{configurable:!0,get:function(){b("Module.readBinary has been replaced with plain readBinary (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});Object.getOwnPropertyDescriptor(a,"setWindowTitle")||Object.defineProperty(a,"setWindowTitle",{configurable:!0,get:function(){b("Module.setWindowTitle has been replaced with plain setWindowTitle (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
function ea(c){fa||={};fa[c]||(fa[c]=1,x(c))}var fa,z;a.wasmBinary&&(z=a.wasmBinary);Object.getOwnPropertyDescriptor(a,"wasmBinary")||Object.defineProperty(a,"wasmBinary",{configurable:!0,get:function(){b("Module.wasmBinary has been replaced with plain wasmBinary (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});var noExitRuntime;a.noExitRuntime&&(noExitRuntime=a.noExitRuntime);
Object.getOwnPropertyDescriptor(a,"noExitRuntime")||Object.defineProperty(a,"noExitRuntime",{configurable:!0,get:function(){b("Module.noExitRuntime has been replaced with plain noExitRuntime (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});"object"!==typeof WebAssembly&&b("no native wasm support detected");var A,ha=!1;function y(c,d){c||b("Assertion failed: "+d)}
function ia(c){var d=a["_"+c];y(d,"Cannot call unknown function "+c+", make sure it is exported");return d}
function ja(c,d,e,f){var g={string:function(n){var r=0;if(null!==n&&void 0!==n&&0!==n){var t=(n.length<<2)+1;r=ka(t);la(n,r,t)}return r},array:function(n){var r=ka(n.length);y(0<=n.length,"writeArrayToMemory array must have a length (should be an array or typed array)");B.set(n,r);return r}},h=ia(c),l=[];c=0;y("array"!==d,'Return type should not be "array".');if(f)for(var k=0;k<f.length;k++){var p=g[e[k]];p?(0===c&&(c=ma()),l[k]=p(f[k])):l[k]=f[k]}e=h.apply(null,l);e=function(n){return"string"===
d?n?C(n,void 0):"":"boolean"===d?!!n:n}(e);0!==c&&na(c);return e}var oa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function C(c,d){var e=E,f=c+d;for(d=c;e[d]&&!(d>=f);)++d;if(16<d-c&&e.subarray&&oa)return oa.decode(e.subarray(c,d));for(f="";c<d;){var g=e[c++];if(g&128){var h=e[c++]&63;if(192==(g&224))f+=String.fromCharCode((g&31)<<6|h);else{var l=e[c++]&63;224==(g&240)?g=(g&15)<<12|h<<6|l:(240!=(g&248)&&ea("Invalid UTF-8 leading byte 0x"+g.toString(16)+" encountered when deserializing a UTF-8 string on the asm.js/wasm heap to a JS string!"),g=(g&7)<<18|h<<12|l<<6|e[c++]&63);65536>g?f+=String.fromCharCode(g):(g-=
65536,f+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else f+=String.fromCharCode(g)}return f}
function la(c,d,e){y("number"==typeof e,"stringToUTF8(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");var f=E;if(0<e){e=d+e-1;for(var g=0;g<c.length;++g){var h=c.charCodeAt(g);if(55296<=h&&57343>=h){var l=c.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(d>=e)break;f[d++]=h}else{if(2047>=h){if(d+1>=e)break;f[d++]=192|h>>6}else{if(65535>=h){if(d+2>=e)break;f[d++]=224|h>>12}else{if(d+3>=e)break;2097152<=h&&ea("Invalid Unicode code point 0x"+
h.toString(16)+" encountered when serializing a JS string to an UTF-8 string on the asm.js/wasm heap! (Valid unicode code points should be in range 0-0x1FFFFF).");f[d++]=240|h>>18;f[d++]=128|h>>12&63}f[d++]=128|h>>6&63}f[d++]=128|h&63}}f[d]=0}}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function qa(c,d){y(0==c%2,"Pointer passed to UTF16ToString must be aligned to two bytes!");var e=c>>1;for(var f=e+d/2;!(e>=f)&&ra[e];)++e;e<<=1;if(32<e-c&&pa)return pa.decode(E.subarray(c,e));e="";for(f=0;!(f>=d/2);++f){var g=F[c+2*f>>1];if(0==g)break;e+=String.fromCharCode(g)}return e}
function sa(c,d,e){y(0==d%2,"Pointer passed to stringToUTF16 must be aligned to two bytes!");y("number"==typeof e,"stringToUTF16(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");void 0===e&&(e=2147483647);if(2>e)return 0;e-=2;var f=d;e=e<2*c.length?e/2:c.length;for(var g=0;g<e;++g)F[d>>1]=c.charCodeAt(g),d+=2;F[d>>1]=0;return d-f}function ta(c){return 2*c.length}
function ua(c,d){y(0==c%4,"Pointer passed to UTF32ToString must be aligned to four bytes!");for(var e=0,f="";!(e>=d/4);){var g=H[c+4*e>>2];if(0==g)break;++e;65536<=g?(g-=65536,f+=String.fromCharCode(55296|g>>10,56320|g&1023)):f+=String.fromCharCode(g)}return f}
function va(c,d,e){y(0==d%4,"Pointer passed to stringToUTF32 must be aligned to four bytes!");y("number"==typeof e,"stringToUTF32(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");void 0===e&&(e=2147483647);if(4>e)return 0;var f=d;e=f+e-4;for(var g=0;g<c.length;++g){var h=c.charCodeAt(g);if(55296<=h&&57343>=h){var l=c.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}H[d>>2]=h;d+=4;if(d+4>e)break}H[d>>2]=0;return d-f}
function wa(c){for(var d=0,e=0;e<c.length;++e){var f=c.charCodeAt(e);55296<=f&&57343>=f&&++e;d+=4}return d}var xa,B,E,F,ra,H,I,ya,za;function Aa(){var c=A.buffer;xa=c;a.HEAP8=B=new Int8Array(c);a.HEAP16=F=new Int16Array(c);a.HEAP32=H=new Int32Array(c);a.HEAPU8=E=new Uint8Array(c);a.HEAPU16=ra=new Uint16Array(c);a.HEAPU32=I=new Uint32Array(c);a.HEAPF32=ya=new Float32Array(c);a.HEAPF64=za=new Float64Array(c)}a.TOTAL_STACK&&y(5242880===a.TOTAL_STACK,"the stack size can no longer be determined at runtime");
var Ba=a.INITIAL_MEMORY||16777216;Object.getOwnPropertyDescriptor(a,"INITIAL_MEMORY")||Object.defineProperty(a,"INITIAL_MEMORY",{configurable:!0,get:function(){b("Module.INITIAL_MEMORY has been replaced with plain INITIAL_MEMORY (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});y(5242880<=Ba,"INITIAL_MEMORY should be larger than TOTAL_STACK, was "+Ba+"! (TOTAL_STACK=5242880)");
y("undefined"!==typeof Int32Array&&"undefined"!==typeof Float64Array&&void 0!==Int32Array.prototype.subarray&&void 0!==Int32Array.prototype.set,"JS engine does not provide full typed array support");y(!a.wasmMemory,"Use of `wasmMemory` detected.  Use -s IMPORTED_MEMORY to define wasmMemory externally");y(16777216==Ba,"Detected runtime INITIAL_MEMORY setting.  Use -s IMPORTED_MEMORY to define wasmMemory dynamically");var J;
function Ca(){var c=Da();y(0==(c&3));I[(c>>2)+1]=34821223;I[(c>>2)+2]=2310721022;H[0]=1668509029}function K(){if(!ha){var c=Da(),d=I[(c>>2)+1];c=I[(c>>2)+2];34821223==d&&2310721022==c||b("Stack overflow! Stack cookie has been overwritten, expected hex dwords 0x89BACDFE and 0x2135467, but received 0x"+c.toString(16)+" "+d.toString(16));1668509029!==H[0]&&b("Runtime error: The application has corrupted its heap memory area (address zero)!")}}var Ea=new Int16Array(1),Fa=new Int8Array(Ea.buffer);
Ea[0]=25459;if(115!==Fa[0]||99!==Fa[1])throw"Runtime error: expected the system to be little-endian!";var Ga=[],Ha=[],Ia=[],Ja=[],Ka=!1;Ha.push({m:function(){La()}});function Ma(){var c=a.preRun.shift();Ga.unshift(c)}y(Math.imul,"This browser does not support Math.imul(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");y(Math.fround,"This browser does not support Math.fround(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");
y(Math.clz32,"This browser does not support Math.clz32(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");y(Math.trunc,"This browser does not support Math.trunc(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");var L=0,N=null,O=null,P={};
function Na(){L++;a.monitorRunDependencies&&a.monitorRunDependencies(L);y(!P["wasm-instantiate"]);P["wasm-instantiate"]=1;null===N&&"undefined"!==typeof setInterval&&(N=setInterval(function(){if(ha)clearInterval(N),N=null;else{var c=!1,d;for(d in P)c||(c=!0,x("still waiting on run dependencies:")),x("dependency: "+d);c&&x("(end of list)")}},1E4))}a.preloadedImages={};a.preloadedAudios={};
function b(c){if(a.onAbort)a.onAbort(c);x(c);ha=!0;c="abort("+c+") at ";a:{var d=Error();if(!d.stack){try{throw Error();}catch(e){d=e}if(!d.stack){d="(no stack trace available)";break a}}d=d.stack.toString()}a.extraStackTrace&&(d+="\n"+a.extraStackTrace());d=Oa(d);c+=d;c=new WebAssembly.RuntimeError(c);ba(c);throw c;}
function Pa(){b("Filesystem support (FS) was not included. The problem is that you are using files from JS, but files were not used from C/C++, so filesystem support was not auto-included. You can force-include filesystem support with  -s FORCE_FILESYSTEM=1")}a.FS_createDataFile=function(){Pa()};a.FS_createPreloadedFile=function(){Pa()};function Qa(c){var d=Q;return String.prototype.startsWith?d.startsWith(c):0===d.indexOf(c)}function Ra(){return Qa("data:application/octet-stream;base64,")}
function S(c){return function(){var d=a.asm;y(Ka,"native function `"+c+"` called before runtime initialization");y(!0,"native function `"+c+"` called after runtime exit (use NO_EXIT_RUNTIME to keep it alive after main() exits)");d[c]||y(d[c],"exported native function `"+c+"` not found");return d[c].apply(null,arguments)}}var Q="noita_random.wasm";if(!Ra()){var Sa=Q;Q=a.locateFile?a.locateFile(Sa,w):w+Sa}
function Ta(){var c=Q;try{if(c==Q&&z)return new Uint8Array(z);if(da)return da(c);throw"both async and sync fetching of the wasm failed";}catch(d){b(d)}}function Ua(){return z||!ca&&!v||"function"!==typeof fetch?Promise.resolve().then(function(){return Ta()}):fetch(Q,{credentials:"same-origin"}).then(function(c){if(!c.ok)throw"failed to load wasm binary file at '"+Q+"'";return c.arrayBuffer()}).catch(function(){return Ta()})}
function Va(c){for(;0<c.length;){var d=c.shift();if("function"==typeof d)d(a);else{var e=d.m;"number"===typeof e?void 0===d.j?J.get(e)():J.get(e)(d.j):e(void 0===d.j?null:d.j)}}}function Oa(c){return c.replace(/\b_Z[\w\d_]+/g,function(d){ea("warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling");return d===d?d:d+" ["+d+"]"})}
function Wa(c){this.i=c-16;this.D=function(d){H[this.i+8>>2]=d};this.A=function(d){H[this.i+0>>2]=d};this.B=function(){H[this.i+4>>2]=0};this.v=function(){B[this.i+12>>0]=0};this.C=function(){B[this.i+13>>0]=0};this.s=function(d,e){this.D(d);this.A(e);this.B();this.v();this.C()}}var Za=0;function $a(c){switch(c){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+c);}}var ab=void 0;
function T(c){for(var d="";E[c];)d+=ab[E[c++]];return d}var U={},V={},bb={};function cb(c){if(void 0===c)return"_unknown";c=c.replace(/[^a-zA-Z0-9_]/g,"$");var d=c.charCodeAt(0);return 48<=d&&57>=d?"_"+c:c}function db(c,d){c=cb(c);return(new Function("body","return function "+c+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(d)}
function eb(c){var d=Error,e=db(c,function(f){this.name=c;this.message=f;f=Error(f).stack;void 0!==f&&(this.stack=this.toString()+"\n"+f.replace(/^Error(:[^\n]*)?\n/,""))});e.prototype=Object.create(d.prototype);e.prototype.constructor=e;e.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return e}var fb=void 0;function W(c){throw new fb(c);}var gb=void 0;
function hb(c,d){function e(k){k=d(k);if(k.length!==f.length)throw new gb("Mismatched type converter count");for(var p=0;p<f.length;++p)X(f[p],k[p])}var f=[];f.forEach(function(k){bb[k]=c});var g=Array(c.length),h=[],l=0;c.forEach(function(k,p){V.hasOwnProperty(k)?g[p]=V[k]:(h.push(k),U.hasOwnProperty(k)||(U[k]=[]),U[k].push(function(){g[p]=V[k];++l;l===h.length&&e(g)}))});0===h.length&&e(g)}
function X(c,d,e){e=e||{};if(!("argPackAdvance"in d))throw new TypeError("registerType registeredInstance requires argPackAdvance");var f=d.name;c||W('type "'+f+'" must have a positive integer typeid pointer');if(V.hasOwnProperty(c)){if(e.o)return;W("Cannot register type '"+f+"' twice")}V[c]=d;delete bb[c];U.hasOwnProperty(c)&&(d=U[c],delete U[c],d.forEach(function(g){g()}))}var ib=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function jb(c){switch(c){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var d=ib.length?ib.pop():Y.length;Y[d]={u:1,value:c};return d}}function kb(c){return this.fromWireType(I[c>>2])}function lb(c){if(null===c)return"null";var d=typeof c;return"object"===d||"array"===d||"function"===d?c.toString():""+c}
function mb(c,d){switch(d){case 2:return function(e){return this.fromWireType(ya[e>>2])};case 3:return function(e){return this.fromWireType(za[e>>3])};default:throw new TypeError("Unknown float type: "+c);}}function nb(c){var d=Function;if(!(d instanceof Function))throw new TypeError("new_ called with constructor type "+typeof d+" which is not a function");var e=db(d.name||"unknownFunctionName",function(){});e.prototype=d.prototype;e=new e;c=d.apply(e,c);return c instanceof Object?c:e}
function ob(c){for(;c.length;){var d=c.pop();c.pop()(d)}}function pb(c,d){var e=a;if(void 0===e[c].g){var f=e[c];e[c]=function(){e[c].g.hasOwnProperty(arguments.length)||W("Function '"+d+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+e[c].g+")!");return e[c].g[arguments.length].apply(this,arguments)};e[c].g=[];e[c].g[f.l]=f}}
function qb(c,d,e){a.hasOwnProperty(c)?((void 0===e||void 0!==a[c].g&&void 0!==a[c].g[e])&&W("Cannot register public name '"+c+"' twice"),pb(c,c),a.hasOwnProperty(e)&&W("Cannot register multiple overloads of a function with the same number of arguments ("+e+")!"),a[c].g[e]=d):(a[c]=d,void 0!==e&&(a[c].G=e))}function rb(c,d){for(var e=[],f=0;f<c;f++)e.push(H[(d>>2)+f]);return e}
function sb(c,d){y(0<=c.indexOf("j"),"getDynCaller should only be called with i64 sigs");var e=[];return function(){e.length=arguments.length;for(var f=0;f<arguments.length;f++)e[f]=arguments[f];-1!=c.indexOf("j")?(y("dynCall_"+c in a,"bad function pointer type - no table for sig '"+c+"'"),e&&e.length?y(e.length===c.substring(1).replace(/j/g,"--").length):y(1==c.length),f=a["dynCall_"+c],f=e&&e.length?f.apply(null,[d].concat(e)):f.call(null,d)):(y(J.get(d),"missing table entry in dynCall: "+d),f=
J.get(d).apply(null,e));return f}}function tb(c,d){c=T(c);var e=-1!=c.indexOf("j")?sb(c,d):J.get(d);"function"!==typeof e&&W("unknown function pointer with signature "+c+": "+d);return e}var ub=void 0;function vb(c){c=wb(c);var d=T(c);Z(c);return d}function xb(c,d){function e(h){g[h]||V[h]||(bb[h]?bb[h].forEach(e):(f.push(h),g[h]=!0))}var f=[],g={};d.forEach(e);throw new ub(c+": "+f.map(vb).join([", "]));}
function yb(c,d,e){switch(d){case 0:return e?function(f){return B[f]}:function(f){return E[f]};case 1:return e?function(f){return F[f>>1]}:function(f){return ra[f>>1]};case 2:return e?function(f){return H[f>>2]}:function(f){return I[f>>2]};default:throw new TypeError("Unknown integer type: "+c);}}for(var zb=Array(256),Ab=0;256>Ab;++Ab)zb[Ab]=String.fromCharCode(Ab);ab=zb;fb=a.BindingError=eb("BindingError");gb=a.InternalError=eb("InternalError");
a.count_emval_handles=function(){for(var c=0,d=5;d<Y.length;++d)void 0!==Y[d]&&++c;return c};a.get_first_emval=function(){for(var c=5;c<Y.length;++c)if(void 0!==Y[c])return Y[c];return null};ub=a.UnboundTypeError=eb("UnboundTypeError");
var Cb={__assert_fail:function(c,d,e,f){b("Assertion failed: "+(c?C(c,void 0):"")+", at: "+[d?d?C(d,void 0):"":"unknown filename",e,f?f?C(f,void 0):"":"unknown function"])},__cxa_allocate_exception:function(c){return Bb(c+16)+16},__cxa_atexit:function(){},__cxa_throw:function(c,d,e){(new Wa(c)).s(d,e);Za++;throw c+" - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.";},_embind_register_bool:function(c,
d,e,f,g){var h=$a(e);d=T(d);X(c,{name:d,fromWireType:function(l){return!!l},toWireType:function(l,k){return k?f:g},argPackAdvance:8,readValueFromPointer:function(l){if(1===e)var k=B;else if(2===e)k=F;else if(4===e)k=H;else throw new TypeError("Unknown boolean type size: "+d);return this.fromWireType(k[l>>h])},h:null})},_embind_register_emval:function(c,d){d=T(d);X(c,{name:d,fromWireType:function(e){var f=Y[e].value;4<e&&0===--Y[e].u&&(Y[e]=void 0,ib.push(e));return f},toWireType:function(e,f){return jb(f)},
argPackAdvance:8,readValueFromPointer:kb,h:null})},_embind_register_float:function(c,d,e){e=$a(e);d=T(d);X(c,{name:d,fromWireType:function(f){return f},toWireType:function(f,g){if("number"!==typeof g&&"boolean"!==typeof g)throw new TypeError('Cannot convert "'+lb(g)+'" to '+this.name);return g},argPackAdvance:8,readValueFromPointer:mb(d,e),h:null})},_embind_register_function:function(c,d,e,f,g,h){var l=rb(d,e);c=T(c);g=tb(f,g);qb(c,function(){xb("Cannot call "+c+" due to unbound types",l)},d-1);hb(l,
function(k){var p=c,n=c;k=[k[0],null].concat(k.slice(1));var r=g,t=k.length;2>t&&W("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var D=null!==k[1]&&!1,G=!1,q=1;q<k.length;++q)if(null!==k[q]&&void 0===k[q].h){G=!0;break}var Xa="void"!==k[0].name,M="",R="";for(q=0;q<t-2;++q)M+=(0!==q?", ":"")+"arg"+q,R+=(0!==q?", ":"")+"arg"+q+"Wired";n="return function "+cb(n)+"("+M+") {\nif (arguments.length !== "+(t-2)+") {\nthrowBindingError('function "+n+" called with ' + arguments.length + ' arguments, expected "+
(t-2)+" args!');\n}\n";G&&(n+="var destructors = [];\n");var Ya=G?"destructors":"null";M="throwBindingError invoker fn runDestructors retType classParam".split(" ");r=[W,r,h,ob,k[0],k[1]];D&&(n+="var thisWired = classParam.toWireType("+Ya+", this);\n");for(q=0;q<t-2;++q)n+="var arg"+q+"Wired = argType"+q+".toWireType("+Ya+", arg"+q+"); // "+k[q+2].name+"\n",M.push("argType"+q),r.push(k[q+2]);D&&(R="thisWired"+(0<R.length?", ":"")+R);n+=(Xa?"var rv = ":"")+"invoker(fn"+(0<R.length?", ":"")+R+");\n";
if(G)n+="runDestructors(destructors);\n";else for(q=D?1:2;q<k.length;++q)t=1===q?"thisWired":"arg"+(q-2)+"Wired",null!==k[q].h&&(n+=t+"_dtor("+t+"); // "+k[q].name+"\n",M.push(t+"_dtor"),r.push(k[q].h));Xa&&(n+="var ret = retType.fromWireType(rv);\nreturn ret;\n");M.push(n+"}\n");k=nb(M).apply(null,r);q=d-1;if(!a.hasOwnProperty(p))throw new gb("Replacing nonexistant public symbol");void 0!==a[p].g&&void 0!==q?a[p].g[q]=k:(a[p]=k,a[p].l=q);return[]})},_embind_register_integer:function(c,d,e,f,g){function h(n){return n}
d=T(d);-1===g&&(g=4294967295);var l=$a(e);if(0===f){var k=32-8*e;h=function(n){return n<<k>>>k}}var p=-1!=d.indexOf("unsigned");X(c,{name:d,fromWireType:h,toWireType:function(n,r){if("number"!==typeof r&&"boolean"!==typeof r)throw new TypeError('Cannot convert "'+lb(r)+'" to '+this.name);if(r<f||r>g)throw new TypeError('Passing a number "'+lb(r)+'" from JS side to C/C++ side to an argument of type "'+d+'", which is outside the valid range ['+f+", "+g+"]!");return p?r>>>0:r|0},argPackAdvance:8,readValueFromPointer:yb(d,
l,0!==f),h:null})},_embind_register_memory_view:function(c,d,e){function f(h){h>>=2;var l=I;return new g(xa,l[h+1],l[h])}var g=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][d];e=T(e);X(c,{name:e,fromWireType:f,argPackAdvance:8,readValueFromPointer:f},{o:!0})},_embind_register_std_string:function(c,d){d=T(d);var e="std::string"===d;X(c,{name:d,fromWireType:function(f){var g=I[f>>2];if(e)for(var h=f+4,l=0;l<=g;++l){var k=f+4+l;if(l==g||0==E[k]){h=h?C(h,
k-h):"";if(void 0===p)var p=h;else p+=String.fromCharCode(0),p+=h;h=k+1}}else{p=Array(g);for(l=0;l<g;++l)p[l]=String.fromCharCode(E[f+4+l]);p=p.join("")}Z(f);return p},toWireType:function(f,g){g instanceof ArrayBuffer&&(g=new Uint8Array(g));var h="string"===typeof g;h||g instanceof Uint8Array||g instanceof Uint8ClampedArray||g instanceof Int8Array||W("Cannot pass non-string to std::string");var l=(e&&h?function(){for(var n=0,r=0;r<g.length;++r){var t=g.charCodeAt(r);55296<=t&&57343>=t&&(t=65536+((t&
1023)<<10)|g.charCodeAt(++r)&1023);127>=t?++n:n=2047>=t?n+2:65535>=t?n+3:n+4}return n}:function(){return g.length})(),k=Bb(4+l+1);I[k>>2]=l;if(e&&h)la(g,k+4,l+1);else if(h)for(h=0;h<l;++h){var p=g.charCodeAt(h);255<p&&(Z(k),W("String has UTF-16 code units that do not fit in 8 bits"));E[k+4+h]=p}else for(h=0;h<l;++h)E[k+4+h]=g[h];null!==f&&f.push(Z,k);return k},argPackAdvance:8,readValueFromPointer:kb,h:function(f){Z(f)}})},_embind_register_std_wstring:function(c,d,e){e=T(e);if(2===d){var f=qa;var g=
sa;var h=ta;var l=function(){return ra};var k=1}else 4===d&&(f=ua,g=va,h=wa,l=function(){return I},k=2);X(c,{name:e,fromWireType:function(p){for(var n=I[p>>2],r=l(),t,D=p+4,G=0;G<=n;++G){var q=p+4+G*d;if(G==n||0==r[q>>k])D=f(D,q-D),void 0===t?t=D:(t+=String.fromCharCode(0),t+=D),D=q+d}Z(p);return t},toWireType:function(p,n){"string"!==typeof n&&W("Cannot pass non-string to C++ string type "+e);var r=h(n),t=Bb(4+r+d);I[t>>2]=r>>k;g(n,t+4,r+d);null!==p&&p.push(Z,t);return t},argPackAdvance:8,readValueFromPointer:kb,
h:function(p){Z(p)}})},_embind_register_void:function(c,d){d=T(d);X(c,{F:!0,name:d,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},abort:function(){b()},emscripten_memcpy_big:function(c,d,e){E.copyWithin(c,d,d+e)},emscripten_resize_heap:function(c){c>>>=0;var d=E.length;y(c>d);if(2147483648<c)return x("Cannot enlarge memory, asked to go up to "+c+" bytes, but the limit is 2147483648 bytes!"),!1;for(var e=1;4>=e;e*=2){var f=d*(1+.2/e);f=Math.min(f,c+100663296);f=Math.max(16777216,
c,f);0<f%65536&&(f+=65536-f%65536);f=Math.min(2147483648,f);a:{var g=f;try{A.grow(g-xa.byteLength+65535>>>16);Aa();var h=1;break a}catch(l){console.error("emscripten_realloc_buffer: Attempted to grow heap from "+xa.byteLength+" bytes to "+g+" bytes, but got error: "+l)}h=void 0}if(h)return!0}x("Failed to grow the heap from "+d+" bytes to "+f+" bytes, not enough memory!");return!1}};
(function(){function c(h){a.asm=h.exports;A=a.asm.memory;y(A,"memory not found in wasm exports");Aa();J=a.asm.__indirect_function_table;y(J,"table not found in wasm exports");L--;a.monitorRunDependencies&&a.monitorRunDependencies(L);y(P["wasm-instantiate"]);delete P["wasm-instantiate"];0==L&&(null!==N&&(clearInterval(N),N=null),O&&(h=O,O=null,h()))}function d(h){y(a===g,"the Module object should not be replaced during async compilation - perhaps the order of HTML elements is wrong?");g=null;c(h.instance)}
function e(h){return Ua().then(function(l){return WebAssembly.instantiate(l,f)}).then(h,function(l){x("failed to asynchronously prepare wasm: "+l);Qa("file://")&&x("warning: Loading from a file URI ("+Q+") is not supported in most browsers. See https://emscripten.org/docs/getting_started/FAQ.html#how-do-i-run-a-local-webserver-for-testing-why-does-my-program-stall-in-downloading-or-preparing");b(l)})}var f={env:Cb,wasi_snapshot_preview1:Cb};Na();var g=a;if(a.instantiateWasm)try{return a.instantiateWasm(f,
c)}catch(h){return x("Module.instantiateWasm callback failed with error: "+h),!1}(function(){return z||"function"!==typeof WebAssembly.instantiateStreaming||Ra()||"function"!==typeof fetch?e(d):fetch(Q,{credentials:"same-origin"}).then(function(h){return WebAssembly.instantiateStreaming(h,f).then(d,function(l){x("wasm streaming compile failed: "+l);x("falling back to ArrayBuffer instantiation");return e(d)})})})().catch(ba);return{}})();
var La=a.___wasm_call_ctors=S("__wasm_call_ctors"),Z=a._free=S("free"),Bb=a._malloc=S("malloc");a._generate_map=S("generate_map");var wb=a.___getTypeName=S("__getTypeName");a.___embind_register_native_and_builtin_types=S("__embind_register_native_and_builtin_types");a.___errno_location=S("__errno_location");
var ma=a.stackSave=S("stackSave"),na=a.stackRestore=S("stackRestore"),ka=a.stackAlloc=S("stackAlloc"),Db=a._emscripten_stack_init=function(){return(Db=a._emscripten_stack_init=a.asm.emscripten_stack_init).apply(null,arguments)};a._emscripten_stack_get_free=function(){return(a._emscripten_stack_get_free=a.asm.emscripten_stack_get_free).apply(null,arguments)};var Da=a._emscripten_stack_get_end=function(){return(Da=a._emscripten_stack_get_end=a.asm.emscripten_stack_get_end).apply(null,arguments)};
a._setThrew=S("setThrew");Object.getOwnPropertyDescriptor(a,"intArrayFromString")||(a.intArrayFromString=function(){b("'intArrayFromString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"intArrayToString")||(a.intArrayToString=function(){b("'intArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ccall")||(a.ccall=function(){b("'ccall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
a.cwrap=function(c,d,e){return function(){return ja(c,d,e,arguments)}};Object.getOwnPropertyDescriptor(a,"setValue")||(a.setValue=function(){b("'setValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getValue")||(a.getValue=function(){b("'getValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"allocate")||(a.allocate=function(){b("'allocate' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"UTF8ArrayToString")||(a.UTF8ArrayToString=function(){b("'UTF8ArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UTF8ToString")||(a.UTF8ToString=function(){b("'UTF8ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToUTF8Array")||(a.stringToUTF8Array=function(){b("'stringToUTF8Array' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"stringToUTF8")||(a.stringToUTF8=function(){b("'stringToUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"lengthBytesUTF8")||(a.lengthBytesUTF8=function(){b("'lengthBytesUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stackTrace")||(a.stackTrace=function(){b("'stackTrace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"addOnPreRun")||(a.addOnPreRun=function(){b("'addOnPreRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addOnInit")||(a.addOnInit=function(){b("'addOnInit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addOnPreMain")||(a.addOnPreMain=function(){b("'addOnPreMain' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"addOnExit")||(a.addOnExit=function(){b("'addOnExit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addOnPostRun")||(a.addOnPostRun=function(){b("'addOnPostRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeStringToMemory")||(a.writeStringToMemory=function(){b("'writeStringToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"writeArrayToMemory")||(a.writeArrayToMemory=function(){b("'writeArrayToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeAsciiToMemory")||(a.writeAsciiToMemory=function(){b("'writeAsciiToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addRunDependency")||(a.addRunDependency=function(){b("'addRunDependency' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"removeRunDependency")||(a.removeRunDependency=function(){b("'removeRunDependency' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"FS_createFolder")||(a.FS_createFolder=function(){b("'FS_createFolder' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"FS_createPath")||(a.FS_createPath=function(){b("'FS_createPath' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"FS_createDataFile")||(a.FS_createDataFile=function(){b("'FS_createDataFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"FS_createPreloadedFile")||(a.FS_createPreloadedFile=function(){b("'FS_createPreloadedFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"FS_createLazyFile")||(a.FS_createLazyFile=function(){b("'FS_createLazyFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"FS_createLink")||(a.FS_createLink=function(){b("'FS_createLink' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"FS_createDevice")||(a.FS_createDevice=function(){b("'FS_createDevice' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"FS_unlink")||(a.FS_unlink=function(){b("'FS_unlink' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"getLEB")||(a.getLEB=function(){b("'getLEB' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getFunctionTables")||(a.getFunctionTables=function(){b("'getFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"alignFunctionTables")||(a.alignFunctionTables=function(){b("'alignFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registerFunctions")||(a.registerFunctions=function(){b("'registerFunctions' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addFunction")||(a.addFunction=function(){b("'addFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"removeFunction")||(a.removeFunction=function(){b("'removeFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getFuncWrapper")||(a.getFuncWrapper=function(){b("'getFuncWrapper' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"prettyPrint")||(a.prettyPrint=function(){b("'prettyPrint' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"makeBigInt")||(a.makeBigInt=function(){b("'makeBigInt' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"dynCall")||(a.dynCall=function(){b("'dynCall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getCompilerSetting")||(a.getCompilerSetting=function(){b("'getCompilerSetting' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"print")||(a.print=function(){b("'print' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"printErr")||(a.printErr=function(){b("'printErr' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getTempRet0")||(a.getTempRet0=function(){b("'getTempRet0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"setTempRet0")||(a.setTempRet0=function(){b("'setTempRet0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"callMain")||(a.callMain=function(){b("'callMain' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"abort")||(a.abort=function(){b("'abort' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"stringToNewUTF8")||(a.stringToNewUTF8=function(){b("'stringToNewUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"setFileTime")||(a.setFileTime=function(){b("'setFileTime' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emscripten_realloc_buffer")||(a.emscripten_realloc_buffer=function(){b("'emscripten_realloc_buffer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"ENV")||(a.ENV=function(){b("'ENV' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ERRNO_CODES")||(a.ERRNO_CODES=function(){b("'ERRNO_CODES' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ERRNO_MESSAGES")||(a.ERRNO_MESSAGES=function(){b("'ERRNO_MESSAGES' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"setErrNo")||(a.setErrNo=function(){b("'setErrNo' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"DNS")||(a.DNS=function(){b("'DNS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getHostByName")||(a.getHostByName=function(){b("'getHostByName' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"GAI_ERRNO_MESSAGES")||(a.GAI_ERRNO_MESSAGES=function(){b("'GAI_ERRNO_MESSAGES' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"Protocols")||(a.Protocols=function(){b("'Protocols' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"Sockets")||(a.Sockets=function(){b("'Sockets' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getRandomDevice")||(a.getRandomDevice=function(){b("'getRandomDevice' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"traverseStack")||(a.traverseStack=function(){b("'traverseStack' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UNWIND_CACHE")||(a.UNWIND_CACHE=function(){b("'UNWIND_CACHE' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"withBuiltinMalloc")||(a.withBuiltinMalloc=function(){b("'withBuiltinMalloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"readAsmConstArgsArray")||(a.readAsmConstArgsArray=function(){b("'readAsmConstArgsArray' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"readAsmConstArgs")||(a.readAsmConstArgs=function(){b("'readAsmConstArgs' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"mainThreadEM_ASM")||(a.mainThreadEM_ASM=function(){b("'mainThreadEM_ASM' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"jstoi_q")||(a.jstoi_q=function(){b("'jstoi_q' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"jstoi_s")||(a.jstoi_s=function(){b("'jstoi_s' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getExecutableName")||(a.getExecutableName=function(){b("'getExecutableName' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"listenOnce")||(a.listenOnce=function(){b("'listenOnce' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"autoResumeAudioContext")||(a.autoResumeAudioContext=function(){b("'autoResumeAudioContext' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"dynCallLegacy")||(a.dynCallLegacy=function(){b("'dynCallLegacy' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getDynCaller")||(a.getDynCaller=function(){b("'getDynCaller' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"dynCall")||(a.dynCall=function(){b("'dynCall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"callRuntimeCallbacks")||(a.callRuntimeCallbacks=function(){b("'callRuntimeCallbacks' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"abortStackOverflow")||(a.abortStackOverflow=function(){b("'abortStackOverflow' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"reallyNegative")||(a.reallyNegative=function(){b("'reallyNegative' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"unSign")||(a.unSign=function(){b("'unSign' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"reSign")||(a.reSign=function(){b("'reSign' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"formatString")||(a.formatString=function(){b("'formatString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"PATH")||(a.PATH=function(){b("'PATH' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"PATH_FS")||(a.PATH_FS=function(){b("'PATH_FS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SYSCALLS")||(a.SYSCALLS=function(){b("'SYSCALLS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"syscallMmap2")||(a.syscallMmap2=function(){b("'syscallMmap2' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"syscallMunmap")||(a.syscallMunmap=function(){b("'syscallMunmap' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getSocketFromFD")||(a.getSocketFromFD=function(){b("'getSocketFromFD' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getSocketAddress")||(a.getSocketAddress=function(){b("'getSocketAddress' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"JSEvents")||(a.JSEvents=function(){b("'JSEvents' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registerKeyEventCallback")||(a.registerKeyEventCallback=function(){b("'registerKeyEventCallback' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"specialHTMLTargets")||(a.specialHTMLTargets=function(){b("'specialHTMLTargets' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"maybeCStringToJsString")||(a.maybeCStringToJsString=function(){b("'maybeCStringToJsString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"findEventTarget")||(a.findEventTarget=function(){b("'findEventTarget' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"findCanvasEventTarget")||(a.findCanvasEventTarget=function(){b("'findCanvasEventTarget' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getBoundingClientRect")||(a.getBoundingClientRect=function(){b("'getBoundingClientRect' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"fillMouseEventData")||(a.fillMouseEventData=function(){b("'fillMouseEventData' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"registerMouseEventCallback")||(a.registerMouseEventCallback=function(){b("'registerMouseEventCallback' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registerWheelEventCallback")||(a.registerWheelEventCallback=function(){b("'registerWheelEventCallback' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"registerUiEventCallback")||(a.registerUiEventCallback=function(){b("'registerUiEventCallback' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registerFocusEventCallback")||(a.registerFocusEventCallback=function(){b("'registerFocusEventCallback' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"fillDeviceOrientationEventData")||(a.fillDeviceOrientationEventData=function(){b("'fillDeviceOrientationEventData' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registerDeviceOrientationEventCallback")||(a.registerDeviceOrientationEventCallback=function(){b("'registerDeviceOrientationEventCallback' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"fillDeviceMotionEventData")||(a.fillDeviceMotionEventData=function(){b("'fillDeviceMotionEventData' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registerDeviceMotionEventCallback")||(a.registerDeviceMotionEventCallback=function(){b("'registerDeviceMotionEventCallback' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"screenOrientation")||(a.screenOrientation=function(){b("'screenOrientation' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"fillOrientationChangeEventData")||(a.fillOrientationChangeEventData=function(){b("'fillOrientationChangeEventData' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"registerOrientationChangeEventCallback")||(a.registerOrientationChangeEventCallback=function(){b("'registerOrientationChangeEventCallback' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"fillFullscreenChangeEventData")||(a.fillFullscreenChangeEventData=function(){b("'fillFullscreenChangeEventData' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"registerFullscreenChangeEventCallback")||(a.registerFullscreenChangeEventCallback=function(){b("'registerFullscreenChangeEventCallback' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registerRestoreOldStyle")||(a.registerRestoreOldStyle=function(){b("'registerRestoreOldStyle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"hideEverythingExceptGivenElement")||(a.hideEverythingExceptGivenElement=function(){b("'hideEverythingExceptGivenElement' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"restoreHiddenElements")||(a.restoreHiddenElements=function(){b("'restoreHiddenElements' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"setLetterbox")||(a.setLetterbox=function(){b("'setLetterbox' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"currentFullscreenStrategy")||(a.currentFullscreenStrategy=function(){b("'currentFullscreenStrategy' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"restoreOldWindowedStyle")||(a.restoreOldWindowedStyle=function(){b("'restoreOldWindowedStyle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"softFullscreenResizeWebGLRenderTarget")||(a.softFullscreenResizeWebGLRenderTarget=function(){b("'softFullscreenResizeWebGLRenderTarget' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"doRequestFullscreen")||(a.doRequestFullscreen=function(){b("'doRequestFullscreen' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"fillPointerlockChangeEventData")||(a.fillPointerlockChangeEventData=function(){b("'fillPointerlockChangeEventData' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registerPointerlockChangeEventCallback")||(a.registerPointerlockChangeEventCallback=function(){b("'registerPointerlockChangeEventCallback' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"registerPointerlockErrorEventCallback")||(a.registerPointerlockErrorEventCallback=function(){b("'registerPointerlockErrorEventCallback' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"requestPointerLock")||(a.requestPointerLock=function(){b("'requestPointerLock' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"fillVisibilityChangeEventData")||(a.fillVisibilityChangeEventData=function(){b("'fillVisibilityChangeEventData' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registerVisibilityChangeEventCallback")||(a.registerVisibilityChangeEventCallback=function(){b("'registerVisibilityChangeEventCallback' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"registerTouchEventCallback")||(a.registerTouchEventCallback=function(){b("'registerTouchEventCallback' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"fillGamepadEventData")||(a.fillGamepadEventData=function(){b("'fillGamepadEventData' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"registerGamepadEventCallback")||(a.registerGamepadEventCallback=function(){b("'registerGamepadEventCallback' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registerBeforeUnloadEventCallback")||(a.registerBeforeUnloadEventCallback=function(){b("'registerBeforeUnloadEventCallback' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"fillBatteryEventData")||(a.fillBatteryEventData=function(){b("'fillBatteryEventData' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"battery")||(a.battery=function(){b("'battery' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registerBatteryEventCallback")||(a.registerBatteryEventCallback=function(){b("'registerBatteryEventCallback' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"setCanvasElementSize")||(a.setCanvasElementSize=function(){b("'setCanvasElementSize' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getCanvasElementSize")||(a.getCanvasElementSize=function(){b("'getCanvasElementSize' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"polyfillSetImmediate")||(a.polyfillSetImmediate=function(){b("'polyfillSetImmediate' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"demangle")||(a.demangle=function(){b("'demangle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"demangleAll")||(a.demangleAll=function(){b("'demangleAll' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"jsStackTrace")||(a.jsStackTrace=function(){b("'jsStackTrace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"stackTrace")||(a.stackTrace=function(){b("'stackTrace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getEnvStrings")||(a.getEnvStrings=function(){b("'getEnvStrings' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"checkWasiClock")||(a.checkWasiClock=function(){b("'checkWasiClock' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"flush_NO_FILESYSTEM")||(a.flush_NO_FILESYSTEM=function(){b("'flush_NO_FILESYSTEM' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeI53ToI64")||(a.writeI53ToI64=function(){b("'writeI53ToI64' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeI53ToI64Clamped")||(a.writeI53ToI64Clamped=function(){b("'writeI53ToI64Clamped' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"writeI53ToI64Signaling")||(a.writeI53ToI64Signaling=function(){b("'writeI53ToI64Signaling' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeI53ToU64Clamped")||(a.writeI53ToU64Clamped=function(){b("'writeI53ToU64Clamped' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeI53ToU64Signaling")||(a.writeI53ToU64Signaling=function(){b("'writeI53ToU64Signaling' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"readI53FromI64")||(a.readI53FromI64=function(){b("'readI53FromI64' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"readI53FromU64")||(a.readI53FromU64=function(){b("'readI53FromU64' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"convertI32PairToI53")||(a.convertI32PairToI53=function(){b("'convertI32PairToI53' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"convertU32PairToI53")||(a.convertU32PairToI53=function(){b("'convertU32PairToI53' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"uncaughtExceptionCount")||(a.uncaughtExceptionCount=function(){b("'uncaughtExceptionCount' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"exceptionLast")||(a.exceptionLast=function(){b("'exceptionLast' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"exceptionCaught")||(a.exceptionCaught=function(){b("'exceptionCaught' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ExceptionInfoAttrs")||(a.ExceptionInfoAttrs=function(){b("'ExceptionInfoAttrs' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ExceptionInfo")||(a.ExceptionInfo=function(){b("'ExceptionInfo' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"CatchInfo")||(a.CatchInfo=function(){b("'CatchInfo' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"exception_addRef")||(a.exception_addRef=function(){b("'exception_addRef' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"exception_decRef")||(a.exception_decRef=function(){b("'exception_decRef' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"Browser")||(a.Browser=function(){b("'Browser' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"funcWrappers")||(a.funcWrappers=function(){b("'funcWrappers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getFuncWrapper")||(a.getFuncWrapper=function(){b("'getFuncWrapper' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"setMainLoop")||(a.setMainLoop=function(){b("'setMainLoop' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"tempFixedLengthArray")||(a.tempFixedLengthArray=function(){b("'tempFixedLengthArray' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"miniTempWebGLFloatBuffers")||(a.miniTempWebGLFloatBuffers=function(){b("'miniTempWebGLFloatBuffers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"heapObjectForWebGLType")||(a.heapObjectForWebGLType=function(){b("'heapObjectForWebGLType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"heapAccessShiftForWebGLHeap")||(a.heapAccessShiftForWebGLHeap=function(){b("'heapAccessShiftForWebGLHeap' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GL")||(a.GL=function(){b("'GL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGet")||(a.emscriptenWebGLGet=function(){b("'emscriptenWebGLGet' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"computeUnpackAlignedImageSize")||(a.computeUnpackAlignedImageSize=function(){b("'computeUnpackAlignedImageSize' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGetTexPixelData")||(a.emscriptenWebGLGetTexPixelData=function(){b("'emscriptenWebGLGetTexPixelData' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGetUniform")||(a.emscriptenWebGLGetUniform=function(){b("'emscriptenWebGLGetUniform' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGetVertexAttrib")||(a.emscriptenWebGLGetVertexAttrib=function(){b("'emscriptenWebGLGetVertexAttrib' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeGLArray")||(a.writeGLArray=function(){b("'writeGLArray' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"AL")||(a.AL=function(){b("'AL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"SDL_unicode")||(a.SDL_unicode=function(){b("'SDL_unicode' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SDL_ttfContext")||(a.SDL_ttfContext=function(){b("'SDL_ttfContext' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SDL_audio")||(a.SDL_audio=function(){b("'SDL_audio' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"SDL")||(a.SDL=function(){b("'SDL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SDL_gfx")||(a.SDL_gfx=function(){b("'SDL_gfx' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GLUT")||(a.GLUT=function(){b("'GLUT' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"EGL")||(a.EGL=function(){b("'EGL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GLFW_Window")||(a.GLFW_Window=function(){b("'GLFW_Window' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GLFW")||(a.GLFW=function(){b("'GLFW' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"GLEW")||(a.GLEW=function(){b("'GLEW' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"IDBStore")||(a.IDBStore=function(){b("'IDBStore' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"runAndAbortIfError")||(a.runAndAbortIfError=function(){b("'runAndAbortIfError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"emval_handle_array")||(a.emval_handle_array=function(){b("'emval_handle_array' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emval_free_list")||(a.emval_free_list=function(){b("'emval_free_list' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emval_symbols")||(a.emval_symbols=function(){b("'emval_symbols' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"init_emval")||(a.init_emval=function(){b("'init_emval' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"count_emval_handles")||(a.count_emval_handles=function(){b("'count_emval_handles' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"get_first_emval")||(a.get_first_emval=function(){b("'get_first_emval' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getStringOrSymbol")||(a.getStringOrSymbol=function(){b("'getStringOrSymbol' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"requireHandle")||(a.requireHandle=function(){b("'requireHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emval_newers")||(a.emval_newers=function(){b("'emval_newers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"craftEmvalAllocator")||(a.craftEmvalAllocator=function(){b("'craftEmvalAllocator' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emval_get_global")||(a.emval_get_global=function(){b("'emval_get_global' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emval_methodCallers")||(a.emval_methodCallers=function(){b("'emval_methodCallers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"InternalError")||(a.InternalError=function(){b("'InternalError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"BindingError")||(a.BindingError=function(){b("'BindingError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UnboundTypeError")||(a.UnboundTypeError=function(){b("'UnboundTypeError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"PureVirtualError")||(a.PureVirtualError=function(){b("'PureVirtualError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"init_embind")||(a.init_embind=function(){b("'init_embind' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"throwInternalError")||(a.throwInternalError=function(){b("'throwInternalError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"throwBindingError")||(a.throwBindingError=function(){b("'throwBindingError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"throwUnboundTypeError")||(a.throwUnboundTypeError=function(){b("'throwUnboundTypeError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ensureOverloadTable")||(a.ensureOverloadTable=function(){b("'ensureOverloadTable' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"exposePublicSymbol")||(a.exposePublicSymbol=function(){b("'exposePublicSymbol' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"replacePublicSymbol")||(a.replacePublicSymbol=function(){b("'replacePublicSymbol' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"extendError")||(a.extendError=function(){b("'extendError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"createNamedFunction")||(a.createNamedFunction=function(){b("'createNamedFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registeredInstances")||(a.registeredInstances=function(){b("'registeredInstances' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getBasestPointer")||(a.getBasestPointer=function(){b("'getBasestPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"registerInheritedInstance")||(a.registerInheritedInstance=function(){b("'registerInheritedInstance' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"unregisterInheritedInstance")||(a.unregisterInheritedInstance=function(){b("'unregisterInheritedInstance' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getInheritedInstance")||(a.getInheritedInstance=function(){b("'getInheritedInstance' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getInheritedInstanceCount")||(a.getInheritedInstanceCount=function(){b("'getInheritedInstanceCount' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getLiveInheritedInstances")||(a.getLiveInheritedInstances=function(){b("'getLiveInheritedInstances' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registeredTypes")||(a.registeredTypes=function(){b("'registeredTypes' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"awaitingDependencies")||(a.awaitingDependencies=function(){b("'awaitingDependencies' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"typeDependencies")||(a.typeDependencies=function(){b("'typeDependencies' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registeredPointers")||(a.registeredPointers=function(){b("'registeredPointers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registerType")||(a.registerType=function(){b("'registerType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"whenDependentTypesAreResolved")||(a.whenDependentTypesAreResolved=function(){b("'whenDependentTypesAreResolved' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"embind_charCodes")||(a.embind_charCodes=function(){b("'embind_charCodes' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"embind_init_charCodes")||(a.embind_init_charCodes=function(){b("'embind_init_charCodes' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"readLatin1String")||(a.readLatin1String=function(){b("'readLatin1String' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getTypeName")||(a.getTypeName=function(){b("'getTypeName' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"heap32VectorToArray")||(a.heap32VectorToArray=function(){b("'heap32VectorToArray' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"requireRegisteredType")||(a.requireRegisteredType=function(){b("'requireRegisteredType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getShiftFromSize")||(a.getShiftFromSize=function(){b("'getShiftFromSize' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"integerReadValueFromPointer")||(a.integerReadValueFromPointer=function(){b("'integerReadValueFromPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"enumReadValueFromPointer")||(a.enumReadValueFromPointer=function(){b("'enumReadValueFromPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"floatReadValueFromPointer")||(a.floatReadValueFromPointer=function(){b("'floatReadValueFromPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"simpleReadValueFromPointer")||(a.simpleReadValueFromPointer=function(){b("'simpleReadValueFromPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"runDestructors")||(a.runDestructors=function(){b("'runDestructors' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"new_")||(a.new_=function(){b("'new_' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"craftInvokerFunction")||(a.craftInvokerFunction=function(){b("'craftInvokerFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"embind__requireFunction")||(a.embind__requireFunction=function(){b("'embind__requireFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"tupleRegistrations")||(a.tupleRegistrations=function(){b("'tupleRegistrations' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"structRegistrations")||(a.structRegistrations=function(){b("'structRegistrations' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"genericPointerToWireType")||(a.genericPointerToWireType=function(){b("'genericPointerToWireType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"constNoSmartPtrRawPointerToWireType")||(a.constNoSmartPtrRawPointerToWireType=function(){b("'constNoSmartPtrRawPointerToWireType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"nonConstNoSmartPtrRawPointerToWireType")||(a.nonConstNoSmartPtrRawPointerToWireType=function(){b("'nonConstNoSmartPtrRawPointerToWireType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"init_RegisteredPointer")||(a.init_RegisteredPointer=function(){b("'init_RegisteredPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"RegisteredPointer")||(a.RegisteredPointer=function(){b("'RegisteredPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"RegisteredPointer_getPointee")||(a.RegisteredPointer_getPointee=function(){b("'RegisteredPointer_getPointee' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"RegisteredPointer_destructor")||(a.RegisteredPointer_destructor=function(){b("'RegisteredPointer_destructor' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"RegisteredPointer_deleteObject")||(a.RegisteredPointer_deleteObject=function(){b("'RegisteredPointer_deleteObject' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"RegisteredPointer_fromWireType")||(a.RegisteredPointer_fromWireType=function(){b("'RegisteredPointer_fromWireType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"runDestructor")||(a.runDestructor=function(){b("'runDestructor' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"releaseClassHandle")||(a.releaseClassHandle=function(){b("'releaseClassHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"finalizationGroup")||(a.finalizationGroup=function(){b("'finalizationGroup' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"detachFinalizer_deps")||(a.detachFinalizer_deps=function(){b("'detachFinalizer_deps' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"detachFinalizer")||(a.detachFinalizer=function(){b("'detachFinalizer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"attachFinalizer")||(a.attachFinalizer=function(){b("'attachFinalizer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"makeClassHandle")||(a.makeClassHandle=function(){b("'makeClassHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"init_ClassHandle")||(a.init_ClassHandle=function(){b("'init_ClassHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"ClassHandle")||(a.ClassHandle=function(){b("'ClassHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ClassHandle_isAliasOf")||(a.ClassHandle_isAliasOf=function(){b("'ClassHandle_isAliasOf' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"throwInstanceAlreadyDeleted")||(a.throwInstanceAlreadyDeleted=function(){b("'throwInstanceAlreadyDeleted' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"ClassHandle_clone")||(a.ClassHandle_clone=function(){b("'ClassHandle_clone' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ClassHandle_delete")||(a.ClassHandle_delete=function(){b("'ClassHandle_delete' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"deletionQueue")||(a.deletionQueue=function(){b("'deletionQueue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"ClassHandle_isDeleted")||(a.ClassHandle_isDeleted=function(){b("'ClassHandle_isDeleted' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ClassHandle_deleteLater")||(a.ClassHandle_deleteLater=function(){b("'ClassHandle_deleteLater' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"flushPendingDeletes")||(a.flushPendingDeletes=function(){b("'flushPendingDeletes' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"delayFunction")||(a.delayFunction=function(){b("'delayFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"setDelayFunction")||(a.setDelayFunction=function(){b("'setDelayFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"RegisteredClass")||(a.RegisteredClass=function(){b("'RegisteredClass' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"shallowCopyInternalPointer")||(a.shallowCopyInternalPointer=function(){b("'shallowCopyInternalPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"downcastPointer")||(a.downcastPointer=function(){b("'downcastPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"upcastPointer")||(a.upcastPointer=function(){b("'upcastPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"validateThis")||(a.validateThis=function(){b("'validateThis' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"char_0")||(a.char_0=function(){b("'char_0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"char_9")||(a.char_9=function(){b("'char_9' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"makeLegalFunctionName")||(a.makeLegalFunctionName=function(){b("'makeLegalFunctionName' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"warnOnce")||(a.warnOnce=function(){b("'warnOnce' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stackSave")||(a.stackSave=function(){b("'stackSave' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"stackRestore")||(a.stackRestore=function(){b("'stackRestore' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stackAlloc")||(a.stackAlloc=function(){b("'stackAlloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"AsciiToString")||(a.AsciiToString=function(){b("'AsciiToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"stringToAscii")||(a.stringToAscii=function(){b("'stringToAscii' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UTF16ToString")||(a.UTF16ToString=function(){b("'UTF16ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToUTF16")||(a.stringToUTF16=function(){b("'stringToUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"lengthBytesUTF16")||(a.lengthBytesUTF16=function(){b("'lengthBytesUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UTF32ToString")||(a.UTF32ToString=function(){b("'UTF32ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToUTF32")||(a.stringToUTF32=function(){b("'stringToUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"lengthBytesUTF32")||(a.lengthBytesUTF32=function(){b("'lengthBytesUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"allocateUTF8")||(a.allocateUTF8=function(){b("'allocateUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"allocateUTF8OnStack")||(a.allocateUTF8OnStack=function(){b("'allocateUTF8OnStack' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
a.writeStackCookie=Ca;a.checkStackCookie=K;Object.getOwnPropertyDescriptor(a,"ALLOC_NORMAL")||Object.defineProperty(a,"ALLOC_NORMAL",{configurable:!0,get:function(){b("'ALLOC_NORMAL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});Object.getOwnPropertyDescriptor(a,"ALLOC_STACK")||Object.defineProperty(a,"ALLOC_STACK",{configurable:!0,get:function(){b("'ALLOC_STACK' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});var Eb;
O=function Fb(){Eb||Gb();Eb||(O=Fb)};
function Gb(){function c(){if(!Eb&&(Eb=!0,a.calledRun=!0,!ha)){K();y(!Ka);Ka=!0;Va(Ha);K();Va(Ia);aa(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();y(!a._main,'compiled without a main, but one is present. if you added it from JS, use Module["onRuntimeInitialized"]');K();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var d=a.postRun.shift();Ja.unshift(d)}Va(Ja)}}if(!(0<L)){Db();Ca();if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)Ma();
Va(Ga);0<L||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);c()},1)):c(),K())}}a.run=Gb;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();noExitRuntime=!0;Gb();


  return create_noita_random.ready
}
);
})();
export default create_noita_random;