/* eslint-disable */
/* tslint:disable */

var create_noita_random = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(create_noita_random = {})  {

var g;g||(g=typeof create_noita_random !== 'undefined' ? create_noita_random : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});var ca=Object.assign({},g),ea="object"==typeof window,p="function"==typeof importScripts,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,v="",ha,ia;
if(fa){var fs=require("fs"),ja=require("path");v=p?ja.dirname(v)+"/":__dirname+"/";ha=(a,b)=>{a=a.startsWith("file://")?new URL(a):ja.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ia=a=>{a=ha(a,!0);a.buffer||(a=new Uint8Array(a));return a};process.argv.slice(2);g.inspect=function(){return"[Emscripten Module object]"}}else if(ea||p)p?v=self.location.href:"undefined"!=typeof document&&document.currentScript&&(v=document.currentScript.src),_scriptDir&&(v=_scriptDir),0!==v.indexOf("blob:")?
v=v.substr(0,v.replace(/[?#].*/,"").lastIndexOf("/")+1):v="",ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},p&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ka=g.print||console.log.bind(console),w=g.printErr||console.warn.bind(console);Object.assign(g,ca);ca=null;var x;g.wasmBinary&&(x=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&z("no native wasm support detected");
var la,ma=!1,na="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function A(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&na)return na.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|k:(e&7)<<18|h<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function oa(a,b,c){var d=B;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var h=a.charCodeAt(e);if(55296<=h&&57343>=h){var k=a.charCodeAt(++e);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(b>=c)break;d[b++]=h}else{if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6}else{if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63}d[b++]=128|h>>6&63}d[b++]=128|h&63}}d[b]=0}}var C,B,D,pa,E,F,qa,ra;
function sa(){var a=la.buffer;g.HEAP8=C=new Int8Array(a);g.HEAP16=D=new Int16Array(a);g.HEAP32=E=new Int32Array(a);g.HEAPU8=B=new Uint8Array(a);g.HEAPU16=pa=new Uint16Array(a);g.HEAPU32=F=new Uint32Array(a);g.HEAPF32=qa=new Float32Array(a);g.HEAPF64=ra=new Float64Array(a)}var ta,ua=[],va=[],wa=[];function xa(){var a=g.preRun.shift();ua.unshift(a)}var G=0,ya=null,H=null;
function z(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";w(a);ma=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}function za(a){return a.startsWith("data:application/octet-stream;base64,")}var J;J="noita_random-base.wasm";if(!za(J)){var Aa=J;J=g.locateFile?g.locateFile(Aa,v):v+Aa}function Ba(a){try{if(a==J&&x)return new Uint8Array(x);if(ia)return ia(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function Ca(a){return x||!ea&&!p||"function"!=typeof fetch?Promise.resolve().then(function(){return Ba(a)}):fetch(a,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(function(){return Ba(a)})}function Da(a,b,c){return Ca(a).then(function(d){return WebAssembly.instantiate(d,b)}).then(function(d){return d}).then(c,function(d){w("failed to asynchronously prepare wasm: "+d);z(d)})}
function Ea(a,b){var c=J;return x||"function"!=typeof WebAssembly.instantiateStreaming||za(c)||fa||"function"!=typeof fetch?Da(c,a,b):fetch(c,{credentials:"same-origin"}).then(function(d){return WebAssembly.instantiateStreaming(d,a).then(b,function(e){w("wasm streaming compile failed: "+e);w("falling back to ArrayBuffer instantiation");return Da(c,a,b)})})}function Fa(a){for(;0<a.length;)a.shift()(g)}
function Ga(a){this.P=a-24;this.qa=function(b){F[this.P+4>>2]=b};this.na=function(b){F[this.P+8>>2]=b};this.oa=function(){E[this.P>>2]=0};this.ma=function(){C[this.P+12>>0]=0};this.pa=function(){C[this.P+13>>0]=0};this.ka=function(b,c){this.la();this.qa(b);this.na(c);this.oa();this.ma();this.pa()};this.la=function(){F[this.P+16>>2]=0}}var Ha=0;function Ia(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ja=void 0;
function K(a){for(var b="";B[a];)b+=Ja[B[a++]];return b}var N={},O={},Ka={};function La(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Ma(a,b){a=La(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}
function Na(a){var b=Error,c=Ma(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var P=void 0;function Q(a){throw new P(a);}var Oa=void 0;function Pa(a){throw new Oa(a);}
function R(a,b,c){function d(f){f=c(f);f.length!==a.length&&Pa("Mismatched type converter count");for(var l=0;l<a.length;++l)S(a[l],f[l])}a.forEach(function(f){Ka[f]=b});var e=Array(b.length),h=[],k=0;b.forEach((f,l)=>{O.hasOwnProperty(f)?e[l]=O[f]:(h.push(f),N.hasOwnProperty(f)||(N[f]=[]),N[f].push(()=>{e[l]=O[f];++k;k===h.length&&d(e)}))});0===h.length&&d(e)}
function S(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||Q('type "'+d+'" must have a positive integer typeid pointer');if(O.hasOwnProperty(a)){if(c.va)return;Q("Cannot register type '"+d+"' twice")}O[a]=b;delete Ka[a];N.hasOwnProperty(a)&&(b=N[a],delete N[a],b.forEach(e=>e()))}function Qa(a){Q(a.M.R.O.name+" instance already deleted")}var Ra=!1;function Sa(){}
function Ta(a){--a.count.value;0===a.count.value&&(a.T?a.U.Z(a.T):a.R.O.Z(a.P))}function Ua(a,b,c){if(b===c)return a;if(void 0===c.V)return null;a=Ua(a,b,c.V);return null===a?null:c.sa(a)}var Va={},T=[];function Wa(){for(;T.length;){var a=T.pop();a.M.$=!1;a["delete"]()}}var Xa=void 0,Ya={};function Za(a,b){for(void 0===b&&Q("ptr should not be undefined");a.V;)b=a.ba(b),a=a.V;return Ya[b]}
function $a(a,b){b.R&&b.P||Pa("makeClassHandle requires ptr and ptrType");!!b.U!==!!b.T&&Pa("Both smartPtrType and smartPtr must be specified");b.count={value:1};return ab(Object.create(a,{M:{value:b}}))}function ab(a){if("undefined"===typeof FinalizationRegistry)return ab=b=>b,a;Ra=new FinalizationRegistry(b=>{Ta(b.M)});ab=b=>{var c=b.M;c.T&&Ra.register(b,{M:c},b);return b};Sa=b=>{Ra.unregister(b)};return ab(a)}function U(){}
function bb(a,b,c){if(void 0===a[b].S){var d=a[b];a[b]=function(){a[b].S.hasOwnProperty(arguments.length)||Q("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].S+")!");return a[b].S[arguments.length].apply(this,arguments)};a[b].S=[];a[b].S[d.da]=d}}
function cb(a,b,c){g.hasOwnProperty(a)?((void 0===c||void 0!==g[a].S&&void 0!==g[a].S[c])&&Q("Cannot register public name '"+a+"' twice"),bb(g,a,a),g.hasOwnProperty(c)&&Q("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),g[a].S[c]=b):(g[a]=b,void 0!==c&&(g[a].Ca=c))}function db(a,b,c,d,e,h,k,f){this.name=a;this.constructor=b;this.X=c;this.Z=d;this.V=e;this.ta=h;this.ba=k;this.sa=f;this.ya=[]}
function eb(a,b,c){for(;b!==c;)b.ba||Q("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.ba(a),b=b.V;return a}function fb(a,b){if(null===b)return this.ga&&Q("null is not a valid "+this.name),0;b.M||Q('Cannot pass "'+gb(b)+'" as a '+this.name);b.M.P||Q("Cannot pass deleted object as a pointer of type "+this.name);return eb(b.M.P,b.M.R.O,this.O)}
function hb(a,b){if(null===b){this.ga&&Q("null is not a valid "+this.name);if(this.fa){var c=this.za();null!==a&&a.push(this.Z,c);return c}return 0}b.M||Q('Cannot pass "'+gb(b)+'" as a '+this.name);b.M.P||Q("Cannot pass deleted object as a pointer of type "+this.name);!this.ea&&b.M.R.ea&&Q("Cannot convert argument of type "+(b.M.U?b.M.U.name:b.M.R.name)+" to parameter type "+this.name);c=eb(b.M.P,b.M.R.O,this.O);if(this.fa)switch(void 0===b.M.T&&Q("Passing raw pointer to smart pointer is illegal"),
this.Ba){case 0:b.M.U===this?c=b.M.T:Q("Cannot convert argument of type "+(b.M.U?b.M.U.name:b.M.R.name)+" to parameter type "+this.name);break;case 1:c=b.M.T;break;case 2:if(b.M.U===this)c=b.M.T;else{var d=b.clone();c=this.Aa(c,ib(function(){d["delete"]()}));null!==a&&a.push(this.Z,c)}break;default:Q("Unsupporting sharing policy")}return c}
function jb(a,b){if(null===b)return this.ga&&Q("null is not a valid "+this.name),0;b.M||Q('Cannot pass "'+gb(b)+'" as a '+this.name);b.M.P||Q("Cannot pass deleted object as a pointer of type "+this.name);b.M.R.ea&&Q("Cannot convert argument of type "+b.M.R.name+" to parameter type "+this.name);return eb(b.M.P,b.M.R.O,this.O)}function kb(a){return this.fromWireType(E[a>>2])}
function V(a,b,c,d){this.name=a;this.O=b;this.ga=c;this.ea=d;this.fa=!1;this.Z=this.Aa=this.za=this.ja=this.Ba=this.xa=void 0;void 0!==b.V?this.toWireType=hb:(this.toWireType=d?fb:jb,this.W=null)}function lb(a,b,c){g.hasOwnProperty(a)||Pa("Replacing nonexistant public symbol");void 0!==g[a].S&&void 0!==c?g[a].S[c]=b:(g[a]=b,g[a].da=c)}var mb=[];function nb(a){var b=mb[a];b||(a>=mb.length&&(mb.length=a+1),mb[a]=b=ta.get(a));return b}
function ob(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=g["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=nb(b).apply(null,c);return d}}function W(a,b){a=K(a);var c=a.includes("j")?ob(a,b):nb(b);"function"!=typeof c&&Q("unknown function pointer with signature "+a+": "+b);return c}var pb=void 0;function qb(a){a=rb(a);var b=K(a);X(a);return b}
function Y(a,b){function c(h){e[h]||O[h]||(Ka[h]?Ka[h].forEach(c):(d.push(h),e[h]=!0))}var d=[],e={};b.forEach(c);throw new pb(a+": "+d.map(qb).join([", "]));}function sb(a,b){for(var c=[],d=0;d<a;d++)c.push(F[b+4*d>>2]);return c}function tb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function ub(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ma(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function vb(a,b,c,d,e,h){var k=b.length;2>k&&Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var f=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].W){l=!0;break}var m="void"!==b[0].name,n="",q="";for(c=0;c<k-2;++c)n+=(0!==c?", ":"")+"arg"+c,q+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+La(a)+"("+n+") {\nif (arguments.length !== "+(k-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(k-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var r=l?"destructors":"null";n="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[Q,d,e,tb,b[0],b[1]];f&&(a+="var thisWired = classParam.toWireType("+r+", this);\n");for(c=0;c<k-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+r+", arg"+c+"); // "+b[c+2].name+"\n",n.push("argType"+c),d.push(b[c+2]);f&&(q="thisWired"+(0<q.length?", ":"")+q);a+=(m||h?"var rv = ":"")+"invoker(fn"+(0<q.length?", ":"")+q+");\n";
if(l)a+="runDestructors(destructors);\n";else for(c=f?1:2;c<b.length;++c)h=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].W&&(a+=h+"_dtor("+h+"); // "+b[c].name+"\n",n.push(h+"_dtor"),d.push(b[c].W));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");n.push(a+"}\n");return ub(n).apply(null,d)}
function wb(a,b,c){a instanceof Object||Q(c+' with invalid "this": '+a);a instanceof b.O.constructor||Q(c+' incompatible with "this" of type '+a.constructor.name);a.M.P||Q("cannot call emscripten binding method "+c+" on deleted object");return eb(a.M.P,a.M.R.O,b.O)}var xb=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function yb(a){4<a&&0===--Z[a].ha&&(Z[a]=void 0,xb.push(a))}
var zb=a=>{a||Q("Cannot use deleted val. handle = "+a);return Z[a].value},ib=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=xb.length?xb.pop():Z.length;Z[b]={ha:1,value:a};return b}};function gb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Bb(a,b){switch(b){case 2:return function(c){return this.fromWireType(qa[c>>2])};case 3:return function(c){return this.fromWireType(ra[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Cb(a,b,c){switch(b){case 0:return c?function(d){return C[d]}:function(d){return B[d]};case 1:return c?function(d){return D[d>>1]}:function(d){return pa[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return F[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Db="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function Eb(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&pa[c];)++c;c<<=1;if(32<c-a&&Db)return Db.decode(B.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=D[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function Fb(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=a.charCodeAt(e),b+=2;D[b>>1]=0;return b-d}function Gb(a){return 2*a.length}
function Hb(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function Ib(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var h=a.charCodeAt(e);if(55296<=h&&57343>=h){var k=a.charCodeAt(++e);h=65536+((h&1023)<<10)|k&1023}E[b>>2]=h;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}
function Jb(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var Kb={};function Lb(a){var b=Kb[a];return void 0===b?K(a):b}var Mb=[];function Nb(a){var b=Mb.length;Mb.push(a);return b}function Ob(a,b){var c=O[a];void 0===c&&Q(b+" has unknown type "+qb(a));return c}function Pb(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=Ob(F[b+4*d>>2],"parameter "+d);return c}var Qb=[],Rb=[null,[],[]];
function Sb(a,b,c,d){var e={string:m=>{var n=0;if(null!==m&&void 0!==m&&0!==m){var q=(m.length<<2)+1;n=Tb(q);oa(m,n,q)}return n},array:m=>{var n=Tb(m.length);C.set(m,n);return n}};a=g["_"+a];var h=[],k=0;if(d)for(var f=0;f<d.length;f++){var l=e[c[f]];l?(0===k&&(k=Ub()),h[f]=l(d[f])):h[f]=d[f]}c=a.apply(null,h);return c=function(m){0!==k&&Vb(k);return"string"===b?m?A(B,m):"":"boolean"===b?!!m:m}(c)}for(var Wb=Array(256),Xb=0;256>Xb;++Xb)Wb[Xb]=String.fromCharCode(Xb);Ja=Wb;P=g.BindingError=Na("BindingError");
Oa=g.InternalError=Na("InternalError");U.prototype.isAliasOf=function(a){if(!(this instanceof U&&a instanceof U))return!1;var b=this.M.R.O,c=this.M.P,d=a.M.R.O;for(a=a.M.P;b.V;)c=b.ba(c),b=b.V;for(;d.V;)a=d.ba(a),d=d.V;return b===d&&c===a};
U.prototype.clone=function(){this.M.P||Qa(this);if(this.M.aa)return this.M.count.value+=1,this;var a=ab,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.M;a=a(c.call(b,d,{M:{value:{count:e.count,$:e.$,aa:e.aa,P:e.P,R:e.R,T:e.T,U:e.U}}}));a.M.count.value+=1;a.M.$=!1;return a};U.prototype["delete"]=function(){this.M.P||Qa(this);this.M.$&&!this.M.aa&&Q("Object already scheduled for deletion");Sa(this);Ta(this.M);this.M.aa||(this.M.T=void 0,this.M.P=void 0)};U.prototype.isDeleted=function(){return!this.M.P};
U.prototype.deleteLater=function(){this.M.P||Qa(this);this.M.$&&!this.M.aa&&Q("Object already scheduled for deletion");T.push(this);1===T.length&&Xa&&Xa(Wa);this.M.$=!0;return this};g.getInheritedInstanceCount=function(){return Object.keys(Ya).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in Ya)Ya.hasOwnProperty(b)&&a.push(Ya[b]);return a};g.flushPendingDeletes=Wa;g.setDelayFunction=function(a){Xa=a;T.length&&Xa&&Xa(Wa)};V.prototype.ua=function(a){this.ja&&(a=this.ja(a));return a};
V.prototype.ia=function(a){this.Z&&this.Z(a)};V.prototype.argPackAdvance=8;V.prototype.readValueFromPointer=kb;V.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
V.prototype.fromWireType=function(a){function b(){return this.fa?$a(this.O.X,{R:this.xa,P:c,U:this,T:a}):$a(this.O.X,{R:this,P:a})}var c=this.ua(a);if(!c)return this.ia(a),null;var d=Za(this.O,c);if(void 0!==d){if(0===d.M.count.value)return d.M.P=c,d.M.T=a,d.clone();d=d.clone();this.ia(a);return d}d=this.O.ta(c);d=Va[d];if(!d)return b.call(this);d=this.ea?d.ra:d.pointerType;var e=Ua(c,this.O,d.O);return null===e?b.call(this):this.fa?$a(d.O.X,{R:d,P:e,U:this,T:a}):$a(d.O.X,{R:d,P:e})};
pb=g.UnboundTypeError=Na("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};
var Zb={a:function(a,b,c,d){z("Assertion failed: "+(a?A(B,a):"")+", at: "+[b?b?A(B,b):"":"unknown filename",c,d?d?A(B,d):"":"unknown function"])},h:function(a,b,c){(new Ga(a)).ka(b,c);Ha++;throw a;},u:function(){},y:function(a,b,c,d,e){var h=Ia(c);b=K(b);S(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,f){return f?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var f=C;else if(2===c)f=D;else if(4===c)f=E;else throw new TypeError("Unknown boolean type size: "+b);
return this.fromWireType(f[k>>h])},W:null})},j:function(a,b,c,d,e,h,k,f,l,m,n,q,r){n=K(n);h=W(e,h);f&&(f=W(k,f));m&&(m=W(l,m));r=W(q,r);var t=La(n);cb(t,function(){Y("Cannot construct "+n+" due to unbound types",[d])});R([a,b,c],d?[d]:[],function(u){u=u[0];if(d){var y=u.O;var L=y.X}else L=U.prototype;u=Ma(t,function(){if(Object.getPrototypeOf(this)!==M)throw new P("Use 'new' to construct "+n);if(void 0===I.Y)throw new P(n+" has no accessible constructor");var Ab=I.Y[arguments.length];if(void 0===
Ab)throw new P("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(I.Y).toString()+") parameters instead!");return Ab.apply(this,arguments)});var M=Object.create(L,{constructor:{value:u}});u.prototype=M;var I=new db(n,u,M,r,y,h,f,m);y=new V(n,I,!0,!1);L=new V(n+"*",I,!1,!1);var da=new V(n+" const*",I,!1,!0);Va[a]={pointerType:L,ra:da};lb(t,u);return[y,L,da]})},i:function(a,b,c,d,e,h){0<b||z();var k=sb(b,c);e=W(d,e);R([],[a],function(f){f=
f[0];var l="constructor "+f.name;void 0===f.O.Y&&(f.O.Y=[]);if(void 0!==f.O.Y[b-1])throw new P("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+f.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");f.O.Y[b-1]=()=>{Y("Cannot construct "+f.name+" due to unbound types",k)};R([],k,function(m){m.splice(1,0,null);f.O.Y[b-1]=vb(l,m,null,e,h);return[]});return[]})},d:function(a,b,c,d,e,h,k,f,l){var m=
sb(c,d);b=K(b);h=W(e,h);R([],[a],function(n){function q(){Y("Cannot call "+r+" due to unbound types",m)}n=n[0];var r=n.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);f&&n.O.ya.push(b);var t=n.O.X,u=t[b];void 0===u||void 0===u.S&&u.className!==n.name&&u.da===c-2?(q.da=c-2,q.className=n.name,t[b]=q):(bb(t,b,r),t[b].S[c-2]=q);R([],m,function(y){y=vb(r,y,n,h,k,l);void 0===t[b].S?(y.da=c-2,t[b]=y):t[b].S[c-2]=y;return[]});return[]})},f:function(a,b,c,d,e,h,k,f,l,m){b=K(b);e=W(d,e);R([],[a],
function(n){n=n[0];var q=n.name+"."+b,r={get:function(){Y("Cannot access "+q+" due to unbound types",[c,k])},enumerable:!0,configurable:!0};r.set=l?()=>{Y("Cannot access "+q+" due to unbound types",[c,k])}:()=>{Q(q+" is a read-only property")};Object.defineProperty(n.O.X,b,r);R([],l?[c,k]:[c],function(t){var u=t[0],y={get:function(){var M=wb(this,n,q+" getter");return u.fromWireType(e(h,M))},enumerable:!0};if(l){l=W(f,l);var L=t[1];y.set=function(M){var I=wb(this,n,q+" setter"),da=[];l(m,I,L.toWireType(da,
M));tb(da)}}Object.defineProperty(n.O.X,b,y);return[]});return[]})},x:function(a,b){b=K(b);S(a,{name:b,fromWireType:function(c){var d=zb(c);yb(c);return d},toWireType:function(c,d){return ib(d)},argPackAdvance:8,readValueFromPointer:kb,W:null})},p:function(a,b,c){c=Ia(c);b=K(b);S(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:Bb(b,c),W:null})},b:function(a,b,c,d,e,h,k){var f=sb(b,c);a=K(a);e=W(d,e);cb(a,function(){Y("Cannot call "+
a+" due to unbound types",f)},b-1);R([],f,function(l){l=[l[0],null].concat(l.slice(1));lb(a,vb(a,l,null,e,h,k),b-1);return[]})},e:function(a,b,c,d,e){b=K(b);-1===e&&(e=4294967295);e=Ia(c);var h=f=>f;if(0===d){var k=32-8*c;h=f=>f<<k>>>k}c=b.includes("unsigned")?function(f,l){return l>>>0}:function(f,l){return l};S(a,{name:b,fromWireType:h,toWireType:c,argPackAdvance:8,readValueFromPointer:Cb(b,e,0!==d),W:null})},c:function(a,b,c){function d(h){h>>=2;var k=F;return new e(k.buffer,k[h+1],k[h])}var e=
[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=K(c);S(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{va:!0})},o:function(a,b){b=K(b);var c="std::string"===b;S(a,{name:b,fromWireType:function(d){var e=F[d>>2],h=d+4;if(c)for(var k=h,f=0;f<=e;++f){var l=h+f;if(f==e||0==B[l]){k=k?A(B,k,l-k):"";if(void 0===m)var m=k;else m+=String.fromCharCode(0),m+=k;k=l+1}}else{m=Array(e);for(f=0;f<e;++f)m[f]=String.fromCharCode(B[h+f]);m=m.join("")}X(d);
return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var h,k="string"==typeof e;k||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||Q("Cannot pass non-string to std::string");if(c&&k)for(var f=h=0;f<e.length;++f){var l=e.charCodeAt(f);127>=l?h++:2047>=l?h+=2:55296<=l&&57343>=l?(h+=4,++f):h+=3}else h=e.length;f=Yb(4+h+1);l=f+4;F[f>>2]=h;if(c&&k)oa(e,l,h+1);else if(k)for(k=0;k<h;++k){var m=e.charCodeAt(k);255<m&&(X(l),Q("String has UTF-16 code units that do not fit in 8 bits"));
B[l+k]=m}else for(k=0;k<h;++k)B[l+k]=e[k];null!==d&&d.push(X,f);return f},argPackAdvance:8,readValueFromPointer:kb,W:function(d){X(d)}})},k:function(a,b,c){c=K(c);if(2===b){var d=Eb;var e=Fb;var h=Gb;var k=()=>pa;var f=1}else 4===b&&(d=Hb,e=Ib,h=Jb,k=()=>F,f=2);S(a,{name:c,fromWireType:function(l){for(var m=F[l>>2],n=k(),q,r=l+4,t=0;t<=m;++t){var u=l+4+t*b;if(t==m||0==n[u>>f])r=d(r,u-r),void 0===q?q=r:(q+=String.fromCharCode(0),q+=r),r=u+b}X(l);return q},toWireType:function(l,m){"string"!=typeof m&&
Q("Cannot pass non-string to C++ string type "+c);var n=h(m),q=Yb(4+n+b);F[q>>2]=n>>f;e(m,q+4,n+b);null!==l&&l.push(X,q);return q},argPackAdvance:8,readValueFromPointer:kb,W:function(l){X(l)}})},z:function(a,b){b=K(b);S(a,{wa:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},s:function(a,b,c,d,e){a=Mb[a];b=zb(b);c=Lb(c);var h=[];F[d>>2]=ib(h);return a(b,c,h,e)},t:function(a,b,c,d){a=Mb[a];b=zb(b);c=Lb(c);a(b,c,null,d)},g:yb,l:function(a,b){var c=Pb(a,b),d=c[0];b=d.name+
"_$"+c.slice(1).map(function(n){return n.name}).join("_")+"$";var e=Qb[b];if(void 0!==e)return e;e=["retType"];for(var h=[d],k="",f=0;f<a-1;++f)k+=(0!==f?", ":"")+"arg"+f,e.push("argType"+f),h.push(c[1+f]);var l="return function "+La("methodCaller_"+b)+"(handle, name, destructors, args) {\n",m=0;for(f=0;f<a-1;++f)l+="    var arg"+f+" = argType"+f+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=c[f+1].argPackAdvance;l+="    var rv = handle[name]("+k+");\n";for(f=0;f<a-1;++f)c[f+1].deleteObject&&
(l+="    argType"+f+".deleteObject(arg"+f+");\n");d.wa||(l+="    return retType.toWireType(destructors, rv);\n");e.push(l+"};\n");a=ub(e).apply(null,h);e=Nb(a);return Qb[b]=e},q:function(a){4<a&&(Z[a].ha+=1)},A:function(a){var b=zb(a);tb(b);yb(a)},r:function(a,b){a=Ob(a,"_emval_take_value");a=a.readValueFromPointer(b);return ib(a)},m:function(){z("")},w:function(a,b,c){B.copyWithin(a,b,b+c)},v:function(a){var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,
a+100663296);var e=Math,h=e.min;d=Math.max(a,d);d+=(65536-d%65536)%65536;a:{var k=la.buffer;try{la.grow(h.call(e,2147483648,d)-k.byteLength+65535>>>16);sa();var f=1;break a}catch(l){}f=void 0}if(f)return!0}return!1},n:function(a,b,c,d){for(var e=0,h=0;h<c;h++){var k=F[b>>2],f=F[b+4>>2];b+=8;for(var l=0;l<f;l++){var m=B[k+l],n=Rb[a];0===m||10===m?((1===a?ka:w)(A(n,0)),n.length=0):n.push(m)}e+=f}F[d>>2]=e;return 0}};
(function(){function a(c){c=c.exports;g.asm=c;la=g.asm.B;sa();ta=g.asm.G;va.unshift(g.asm.C);G--;g.monitorRunDependencies&&g.monitorRunDependencies(G);if(0==G&&(null!==ya&&(clearInterval(ya),ya=null),H)){var d=H;H=null;d()}return c}var b={a:Zb};G++;g.monitorRunDependencies&&g.monitorRunDependencies(G);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){w("Module.instantiateWasm callback failed with error: "+c),ba(c)}Ea(b,function(c){a(c.instance)}).catch(ba);return{}})();
var X=g._free=function(){return(X=g._free=g.asm.D).apply(null,arguments)},Yb=g._malloc=function(){return(Yb=g._malloc=g.asm.E).apply(null,arguments)};g._generate_path_map=function(){return(g._generate_path_map=g.asm.F).apply(null,arguments)};var rb=g.___getTypeName=function(){return(rb=g.___getTypeName=g.asm.H).apply(null,arguments)};g.__embind_initialize_bindings=function(){return(g.__embind_initialize_bindings=g.asm.I).apply(null,arguments)};
function Ub(){return(Ub=g.asm.J).apply(null,arguments)}function Vb(){return(Vb=g.asm.K).apply(null,arguments)}function Tb(){return(Tb=g.asm.L).apply(null,arguments)}g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.N).apply(null,arguments)};g.cwrap=function(a,b,c,d){var e=!c||c.every(h=>"number"===h||"boolean"===h);return"string"!==b&&e&&!d?g["_"+a]:function(){return Sb(a,b,c,arguments)}};var $b;H=function ac(){$b||bc();$b||(H=ac)};
function bc(){function a(){if(!$b&&($b=!0,g.calledRun=!0,!ma)){Fa(va);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();wa.unshift(b)}Fa(wa)}}if(!(0<G)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)xa();Fa(ua);0<G||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();bc();


  return create_noita_random.ready
}

);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = create_noita_random;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return create_noita_random; });
else if (typeof exports === 'object')
  exports["create_noita_random"] = create_noita_random;
