/* eslint-disable */
/* tslint:disable */

var create_noita_random = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(moduleArg = {}) {

var h=moduleArg,ba,ca;h.ready=new Promise((a,b)=>{ba=a;ca=b});var da=Object.assign({},h),ea="object"==typeof window,p="function"==typeof importScripts,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,t="",ha,ia;
if(fa){var fs=require("fs"),ja=require("path");t=p?ja.dirname(t)+"/":__dirname+"/";ha=(a,b)=>{a=a.startsWith("file://")?new URL(a):ja.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ia=a=>{a=ha(a,!0);a.buffer||(a=new Uint8Array(a));return a};process.argv.slice(2);h.inspect=()=>"[Emscripten Module object]"}else if(ea||p)p?t=self.location.href:"undefined"!=typeof document&&document.currentScript&&(t=document.currentScript.src),_scriptDir&&(t=_scriptDir),0!==t.indexOf("blob:")?t=t.substr(0,t.replace(/[?#].*/,
"").lastIndexOf("/")+1):t="",ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},p&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ka=h.print||console.log.bind(console),u=h.printErr||console.error.bind(console);Object.assign(h,da);da=null;var x;h.wasmBinary&&(x=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!=typeof WebAssembly&&la("no native wasm support detected");
var ma,na=!1,oa,y,B,pa,C,D,qa,ra;function sa(){var a=ma.buffer;h.HEAP8=oa=new Int8Array(a);h.HEAP16=B=new Int16Array(a);h.HEAPU8=y=new Uint8Array(a);h.HEAPU16=pa=new Uint16Array(a);h.HEAP32=C=new Int32Array(a);h.HEAPU32=D=new Uint32Array(a);h.HEAPF32=qa=new Float32Array(a);h.HEAPF64=ra=new Float64Array(a)}var ta=[],ua=[],va=[];function wa(){var a=h.preRun.shift();ta.unshift(a)}var E=0,xa=null,F=null;
function la(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";u(a);na=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ca(a);throw a;}function ya(a){return a.startsWith("data:application/octet-stream;base64,")}var G;G="noita_random-base.wasm";if(!ya(G)){var za=G;G=h.locateFile?h.locateFile(za,t):t+za}function Aa(a){if(a==G&&x)return new Uint8Array(x);if(ia)return ia(a);throw"both async and sync fetching of the wasm failed";}
function Ba(a){return x||!ea&&!p||"function"!=typeof fetch?Promise.resolve().then(()=>Aa(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Aa(a))}function Ca(a,b,c){return Ba(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{u(`failed to asynchronously prepare wasm: ${d}`);la(d)})}
function Da(a,b){var c=G;return x||"function"!=typeof WebAssembly.instantiateStreaming||ya(c)||fa||"function"!=typeof fetch?Ca(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){u(`wasm streaming compile failed: ${e}`);u("falling back to ArrayBuffer instantiation");return Ca(c,a,b)}))}
var Ea=a=>{for(;0<a.length;)a.shift()(h)},Fa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,H=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Fa)return Fa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|l:(e&7)<<18|f<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=
String.fromCharCode(e)}return d};function Ga(a){this.P=a-24;this.qa=function(b){D[this.P+4>>2]=b};this.ja=function(b){D[this.P+8>>2]=b};this.ea=function(b,c){this.ia();this.qa(b);this.ja(c)};this.ia=function(){D[this.P+16>>2]=0}}
var Ha=0,Ia=0,Ja,I=a=>{for(var b="";y[a];)b+=Ja[y[a++]];return b},L={},M={},Ka={},N,La=a=>{throw new N(a);},O,Q=(a,b,c)=>{function d(g){g=c(g);if(g.length!==a.length)throw new O("Mismatched type converter count");for(var k=0;k<a.length;++k)P(a[k],g[k])}a.forEach(function(g){Ka[g]=b});var e=Array(b.length),f=[],l=0;b.forEach((g,k)=>{M.hasOwnProperty(g)?e[k]=M[g]:(f.push(g),L.hasOwnProperty(g)||(L[g]=[]),L[g].push(()=>{e[k]=M[g];++l;l===f.length&&d(e)}))});0===f.length&&d(e)};
function Ma(a,b,c={}){var d=b.name;if(!a)throw new N(`type "${d}" must have a positive integer typeid pointer`);if(M.hasOwnProperty(a)){if(c.va)return;throw new N(`Cannot register type '${d}' twice`);}M[a]=b;delete Ka[a];L.hasOwnProperty(a)&&(b=L[a],delete L[a],b.forEach(e=>e()))}function P(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");Ma(a,b,c)}
var Na=a=>{throw new N(a.M.R.O.name+" instance already deleted");},Oa=!1,Pa=()=>{},Qa=(a,b,c)=>{if(b===c)return a;if(void 0===c.T)return null;a=Qa(a,b,c.T);return null===a?null:c.sa(a)},Ra={},R=[],Sa=()=>{for(;R.length;){var a=R.pop();a.M.aa=!1;a["delete"]()}},S,T={},Ta=(a,b)=>{if(void 0===b)throw new N("ptr should not be undefined");for(;a.T;)b=a.da(b),a=a.T;return T[b]},Ua=(a,b)=>{if(!b.R||!b.P)throw new O("makeClassHandle requires ptr and ptrType");if(!!b.V!==!!b.S)throw new O("Both smartPtrType and smartPtr must be specified");
b.count={value:1};return U(Object.create(a,{M:{value:b}}))},U=a=>{if("undefined"===typeof FinalizationRegistry)return U=b=>b,a;Oa=new FinalizationRegistry(b=>{b=b.M;--b.count.value;0===b.count.value&&(b.S?b.V.Y(b.S):b.R.O.Y(b.P))});U=b=>{var c=b.M;c.S&&Oa.register(b,{M:c},b);return b};Pa=b=>{Oa.unregister(b)};return U(a)};function Va(){}var Wa=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};
function Xa(a,b){a=Wa(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}
var Ya=(a,b,c)=>{if(void 0===a[b].U){var d=a[b];a[b]=function(){if(!a[b].U.hasOwnProperty(arguments.length))throw new N(`Function '${c}' called with an invalid number of arguments (${arguments.length}) - expects one of (${a[b].U})!`);return a[b].U[arguments.length].apply(this,arguments)};a[b].U=[];a[b].U[d.fa]=d}},Za=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].U&&void 0!==h[a].U[c])throw new N(`Cannot register public name '${a}' twice`);Ya(h,a,a);if(h.hasOwnProperty(c))throw new N(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].U[c]=b}else h[a]=b,void 0!==c&&(h[a].Ca=c)};function $a(a,b,c,d,e,f,l,g){this.name=a;this.constructor=b;this.Z=c;this.Y=d;this.T=e;this.ta=f;this.da=l;this.sa=g;this.ya=[]}var ab=(a,b,c)=>{for(;b!==c;){if(!b.da)throw new N(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.da(a);b=b.T}return a};
function bb(a,b){if(null===b){if(this.ka)throw new N(`null is not a valid ${this.name}`);return 0}if(!b.M)throw new N(`Cannot pass "${cb(b)}" as a ${this.name}`);if(!b.M.P)throw new N(`Cannot pass deleted object as a pointer of type ${this.name}`);return ab(b.M.P,b.M.R.O,this.O)}
function db(a,b){if(null===b){if(this.ka)throw new N(`null is not a valid ${this.name}`);if(this.ha){var c=this.za();null!==a&&a.push(this.Y,c);return c}return 0}if(!b.M)throw new N(`Cannot pass "${cb(b)}" as a ${this.name}`);if(!b.M.P)throw new N(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.ga&&b.M.R.ga)throw new N(`Cannot convert argument of type ${b.M.V?b.M.V.name:b.M.R.name} to parameter type ${this.name}`);c=ab(b.M.P,b.M.R.O,this.O);if(this.ha){if(void 0===b.M.S)throw new N("Passing raw pointer to smart pointer is illegal");
switch(this.Ba){case 0:if(b.M.V===this)c=b.M.S;else throw new N(`Cannot convert argument of type ${b.M.V?b.M.V.name:b.M.R.name} to parameter type ${this.name}`);break;case 1:c=b.M.S;break;case 2:if(b.M.V===this)c=b.M.S;else{var d=b.clone();c=this.Aa(c,eb(()=>d["delete"]()));null!==a&&a.push(this.Y,c)}break;default:throw new N("Unsupporting sharing policy");}}return c}
function fb(a,b){if(null===b){if(this.ka)throw new N(`null is not a valid ${this.name}`);return 0}if(!b.M)throw new N(`Cannot pass "${cb(b)}" as a ${this.name}`);if(!b.M.P)throw new N(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.M.R.ga)throw new N(`Cannot convert argument of type ${b.M.R.name} to parameter type ${this.name}`);return ab(b.M.P,b.M.R.O,this.O)}function gb(a){return this.fromWireType(D[a>>2])}
function hb(a,b,c,d,e,f,l,g,k,n,m){this.name=a;this.O=b;this.ka=c;this.ga=d;this.ha=e;this.xa=f;this.Ba=l;this.oa=g;this.za=k;this.Aa=n;this.Y=m;e||void 0!==b.T?this.toWireType=db:(this.toWireType=d?bb:fb,this.X=null)}
var ib=(a,b,c)=>{if(!h.hasOwnProperty(a))throw new O("Replacing nonexistant public symbol");void 0!==h[a].U&&void 0!==c?h[a].U[c]=b:(h[a]=b,h[a].fa=c)},jb=[],kb,lb=a=>{var b=jb[a];b||(a>=jb.length&&(jb.length=a+1),jb[a]=b=kb.get(a));return b},mb=(a,b)=>{var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=h["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=lb(b).apply(null,c);return d}},V=(a,b)=>{a=I(a);var c=a.includes("j")?mb(a,b):
lb(b);if("function"!=typeof c)throw new N(`unknown function pointer with signature ${a}: ${b}`);return c},nb,pb=a=>{a=ob(a);var b=I(a);W(a);return b},X=(a,b)=>{function c(f){e[f]||M[f]||(Ka[f]?Ka[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new nb(`${a}: `+d.map(pb).join([", "]));},qb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(D[b+4*d>>2]);return c},rb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function sb(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=Xa(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function tb(a,b,c,d,e,f){var l=b.length;if(2>l)throw new N("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==b[1]&&null!==c,k=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].X){k=!0;break}var n="void"!==b[0].name,m="",q="";for(c=0;c<l-2;++c)m+=(0!==c?", ":"")+"arg"+c,q+=(0!==c?", ":"")+"arg"+c+"Wired";a=`\n        return function ${Wa(a)}(${m}) {\n        if (arguments.length !== ${l-2}) {\n          throwBindingError('function ${a} called with ' + arguments.length + ' arguments, expected ${l-
2}');\n        }`;k&&(a+="var destructors = [];\n");var r=k?"destructors":"null";m="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[La,d,e,rb,b[0],b[1]];g&&(a+="var thisWired = classParam.toWireType("+r+", this);\n");for(c=0;c<l-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+r+", arg"+c+"); // "+b[c+2].name+"\n",m.push("argType"+c),d.push(b[c+2]);g&&(q="thisWired"+(0<q.length?", ":"")+q);a+=(n||f?"var rv = ":"")+"invoker(fn"+(0<q.length?", ":"")+q+");\n";if(k)a+=
"runDestructors(destructors);\n";else for(c=g?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].X&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",m.push(f+"_dtor"),d.push(b[c].X));n&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");m.push(a+"}\n");return sb(m).apply(null,d)}
var ub=(a,b,c)=>{if(!(a instanceof Object))throw new N(`${c} with invalid "this": ${a}`);if(!(a instanceof b.O.constructor))throw new N(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.M.P)throw new N(`cannot call emscripten binding method ${c} on deleted object`);return ab(a.M.P,a.M.R.O,b.O)};function vb(){this.W=[void 0];this.na=[]}
var Y=new vb,wb=a=>{a>=Y.ea&&0===--Y.get(a).pa&&Y.ja(a)},xb=a=>{if(!a)throw new N("Cannot use deleted val. handle = "+a);return Y.get(a).value},eb=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return Y.ia({pa:1,value:a})}};function yb(a){return this.fromWireType(C[a>>2])}
for(var cb=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},Ab=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(qa[c>>2])};case 8:return function(c){return this.fromWireType(ra[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Bb=(a,b,c)=>{switch(b){case 1:return c?d=>oa[d>>0]:d=>y[d>>0];case 2:return c?d=>B[d>>1]:d=>pa[d>>1];case 4:return c?d=>C[d>>2]:d=>D[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);
}},Cb=(a,b,c)=>{var d=y;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var l=a.charCodeAt(++e);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0}},Db=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=
d?(b+=4,++c):b+=3}return b},Eb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Fb=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&pa[c];)++c;c<<=1;if(32<c-a&&Eb)return Eb.decode(y.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=B[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Gb=(a,b,c)=>{void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)B[b>>1]=a.charCodeAt(e),b+=2;B[b>>1]=0;return b-d},Hb=a=>2*a.length,Ib=(a,b)=>
{for(var c=0,d="";!(c>=b/4);){var e=C[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Jb=(a,b,c)=>{void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var l=a.charCodeAt(++e);f=65536+((f&1023)<<10)|l&1023}C[b>>2]=f;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d},Kb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&
++c;b+=4}return b},Lb={},Mb=a=>{var b=Lb[a];return void 0===b?I(a):b},Nb=[],Ob=a=>{var b=Nb.length;Nb.push(a);return b},Pb=(a,b)=>{var c=M[a];if(void 0===c)throw a=b+" has unknown type "+pb(a),new N(a);return c},Qb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Pb(D[b+4*d>>2],"parameter "+d);return c},Rb={},Sb=[null,[],[]],Wb=(a,b,c,d)=>{var e={string:n=>{var m=0;if(null!==n&&void 0!==n&&0!==n){m=Db(n)+1;var q=Tb(m);Cb(n,q,m);m=q}return m},array:n=>{var m=Tb(n.length);oa.set(n,m);return m}};a=h["_"+
a];var f=[],l=0;if(d)for(var g=0;g<d.length;g++){var k=e[c[g]];k?(0===l&&(l=Ub()),f[g]=k(d[g])):f[g]=d[g]}c=a.apply(null,f);return c=function(n){0!==l&&Vb(l);return"string"===b?n?H(y,n):"":"boolean"===b?!!n:n}(c)},Xb=Array(256),Yb=0;256>Yb;++Yb)Xb[Yb]=String.fromCharCode(Yb);Ja=Xb;N=h.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};O=h.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};
Object.assign(Va.prototype,{isAliasOf:function(a){if(!(this instanceof Va&&a instanceof Va))return!1;var b=this.M.R.O,c=this.M.P;a.M=a.M;var d=a.M.R.O;for(a=a.M.P;b.T;)c=b.da(c),b=b.T;for(;d.T;)a=d.da(a),d=d.T;return b===d&&c===a},clone:function(){this.M.P||Na(this);if(this.M.ba)return this.M.count.value+=1,this;var a=U,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.M;a=a(c.call(b,d,{M:{value:{count:e.count,aa:e.aa,ba:e.ba,P:e.P,R:e.R,S:e.S,V:e.V}}}));a.M.count.value+=1;a.M.aa=!1;return a},
["delete"](){this.M.P||Na(this);if(this.M.aa&&!this.M.ba)throw new N("Object already scheduled for deletion");Pa(this);var a=this.M;--a.count.value;0===a.count.value&&(a.S?a.V.Y(a.S):a.R.O.Y(a.P));this.M.ba||(this.M.S=void 0,this.M.P=void 0)},isDeleted:function(){return!this.M.P},deleteLater:function(){this.M.P||Na(this);if(this.M.aa&&!this.M.ba)throw new N("Object already scheduled for deletion");R.push(this);1===R.length&&S&&S(Sa);this.M.aa=!0;return this}});h.getInheritedInstanceCount=()=>Object.keys(T).length;
h.getLiveInheritedInstances=()=>{var a=[],b;for(b in T)T.hasOwnProperty(b)&&a.push(T[b]);return a};h.flushPendingDeletes=Sa;h.setDelayFunction=a=>{S=a;R.length&&S&&S(Sa)};
Object.assign(hb.prototype,{ua(a){this.oa&&(a=this.oa(a));return a},ma(a){this.Y&&this.Y(a)},argPackAdvance:8,readValueFromPointer:gb,deleteObject:function(a){if(null!==a)a["delete"]()},fromWireType:function(a){function b(){return this.ha?Ua(this.O.Z,{R:this.xa,P:c,V:this,S:a}):Ua(this.O.Z,{R:this,P:a})}var c=this.ua(a);if(!c)return this.ma(a),null;var d=Ta(this.O,c);if(void 0!==d){if(0===d.M.count.value)return d.M.P=c,d.M.S=a,d.clone();d=d.clone();this.ma(a);return d}d=this.O.ta(c);d=Ra[d];if(!d)return b.call(this);
d=this.ga?d.ra:d.pointerType;var e=Qa(c,this.O,d.O);return null===e?b.call(this):this.ha?Ua(d.O.Z,{R:d,P:e,V:this,S:a}):Ua(d.O.Z,{R:d,P:e})}});
nb=h.UnboundTypeError=((a,b)=>{var c=Xa(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
Object.assign(vb.prototype,{get(a){return this.W[a]},has(a){return void 0!==this.W[a]},ia(a){var b=this.na.pop()||this.W.length;this.W[b]=a;return b},ja(a){this.W[a]=void 0;this.na.push(a)}});Y.W.push({value:void 0},{value:null},{value:!0},{value:!1});Y.ea=Y.W.length;h.count_emval_handles=()=>{for(var a=0,b=Y.ea;b<Y.W.length;++b)void 0!==Y.W[b]&&++a;return a};
var $b={a:(a,b,c,d)=>{la(`Assertion failed: ${a?H(y,a):""}, at: `+[b?b?H(y,b):"":"unknown filename",c,d?d?H(y,d):"":"unknown function"])},h:(a,b,c)=>{(new Ga(a)).ea(b,c);Ha=a;Ia++;throw Ha;},u:()=>{},y:(a,b,c,d)=>{b=I(b);P(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(y[e])},X:null})},j:(a,b,c,d,e,f,l,g,k,n,m,q,r)=>{m=I(m);f=V(e,f);g&&(g=V(l,g));n&&(n=V(k,n));r=V(q,r);var v=Wa(m);Za(v,
function(){X(`Cannot construct ${m} due to unbound types`,[d])});Q([a,b,c],d?[d]:[],function(w){w=w[0];if(d){var z=w.O;var J=z.Z}else J=Va.prototype;w=Xa(v,function(){if(Object.getPrototypeOf(this)!==K)throw new N("Use 'new' to construct "+m);if(void 0===A.$)throw new N(m+" has no accessible constructor");var zb=A.$[arguments.length];if(void 0===zb)throw new N(`Tried to invoke ctor of ${m} with invalid number of parameters (${arguments.length}) - expected (${Object.keys(A.$).toString()}) parameters instead!`);
return zb.apply(this,arguments)});var K=Object.create(J,{constructor:{value:w}});w.prototype=K;var A=new $a(m,w,K,r,z,f,g,n);A.T&&(void 0===A.T.la&&(A.T.la=[]),A.T.la.push(A));z=new hb(m,A,!0,!1,!1);J=new hb(m+"*",A,!1,!1,!1);var aa=new hb(m+" const*",A,!1,!0,!1);Ra[a]={pointerType:J,ra:aa};ib(v,w);return[z,J,aa]})},i:(a,b,c,d,e,f)=>{var l=qb(b,c);e=V(d,e);Q([],[a],function(g){g=g[0];var k=`constructor ${g.name}`;void 0===g.O.$&&(g.O.$=[]);if(void 0!==g.O.$[b-1])throw new N(`Cannot register multiple constructors with identical number of parameters (${b-
1}) for class '${g.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);g.O.$[b-1]=()=>{X(`Cannot construct ${g.name} due to unbound types`,l)};Q([],l,n=>{n.splice(1,0,null);g.O.$[b-1]=tb(k,n,null,e,f);return[]});return[]})},d:(a,b,c,d,e,f,l,g,k)=>{var n=qb(c,d);b=I(b);f=V(e,f);Q([],[a],function(m){function q(){X(`Cannot call ${r} due to unbound types`,n)}m=m[0];var r=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);g&&m.O.ya.push(b);
var v=m.O.Z,w=v[b];void 0===w||void 0===w.U&&w.className!==m.name&&w.fa===c-2?(q.fa=c-2,q.className=m.name,v[b]=q):(Ya(v,b,r),v[b].U[c-2]=q);Q([],n,function(z){z=tb(r,z,m,f,l,k);void 0===v[b].U?(z.fa=c-2,v[b]=z):v[b].U[c-2]=z;return[]});return[]})},f:(a,b,c,d,e,f,l,g,k,n)=>{b=I(b);e=V(d,e);Q([],[a],function(m){m=m[0];var q=`${m.name}.${b}`,r={get(){X(`Cannot access ${q} due to unbound types`,[c,l])},enumerable:!0,configurable:!0};r.set=k?()=>X(`Cannot access ${q} due to unbound types`,[c,l]):()=>
{throw new N(q+" is a read-only property");};Object.defineProperty(m.O.Z,b,r);Q([],k?[c,l]:[c],function(v){var w=v[0],z={get(){var K=ub(this,m,q+" getter");return w.fromWireType(e(f,K))},enumerable:!0};if(k){k=V(g,k);var J=v[1];z.set=function(K){var A=ub(this,m,q+" setter"),aa=[];k(n,A,J.toWireType(aa,K));rb(aa)}}Object.defineProperty(m.O.Z,b,z);return[]});return[]})},x:(a,b)=>{b=I(b);P(a,{name:b,fromWireType:c=>{var d=xb(c);wb(c);return d},toWireType:(c,d)=>eb(d),argPackAdvance:8,readValueFromPointer:yb,
X:null})},p:(a,b,c)=>{b=I(b);P(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:Ab(b,c),X:null})},b:(a,b,c,d,e,f,l)=>{var g=qb(b,c);a=I(a);e=V(d,e);Za(a,function(){X(`Cannot call ${a} due to unbound types`,g)},b-1);Q([],g,function(k){k=[k[0],null].concat(k.slice(1));ib(a,tb(a,k,null,e,f,l),b-1);return[]})},e:(a,b,c,d,e)=>{b=I(b);-1===e&&(e=4294967295);e=g=>g;if(0===d){var f=32-8*c;e=g=>g<<f>>>f}var l=b.includes("unsigned")?function(g,k){return k>>>0}:function(g,
k){return k};P(a,{name:b,fromWireType:e,toWireType:l,argPackAdvance:8,readValueFromPointer:Bb(b,c,0!==d),X:null})},c:(a,b,c)=>{function d(f){return new e(oa.buffer,D[f+4>>2],D[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=I(c);P(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{va:!0})},o:(a,b)=>{b=I(b);var c="std::string"===b;P(a,{name:b,fromWireType:function(d){var e=D[d>>2],f=d+4;if(c)for(var l=f,g=0;g<=e;++g){var k=
f+g;if(g==e||0==y[k]){l=l?H(y,l,k-l):"";if(void 0===n)var n=l;else n+=String.fromCharCode(0),n+=l;l=k+1}}else{n=Array(e);for(g=0;g<e;++g)n[g]=String.fromCharCode(y[f+g]);n=n.join("")}W(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new N("Cannot pass non-string to std::string");var l=c&&f?Db(e):e.length;var g=Zb(4+l+1),k=g+4;D[g>>2]=l;if(c&&
f)Cb(e,k,l+1);else if(f)for(f=0;f<l;++f){var n=e.charCodeAt(f);if(255<n)throw W(k),new N("String has UTF-16 code units that do not fit in 8 bits");y[k+f]=n}else for(f=0;f<l;++f)y[k+f]=e[f];null!==d&&d.push(W,g);return g},argPackAdvance:8,readValueFromPointer:gb,X(d){W(d)}})},k:(a,b,c)=>{c=I(c);if(2===b){var d=Fb;var e=Gb;var f=Hb;var l=()=>pa;var g=1}else 4===b&&(d=Ib,e=Jb,f=Kb,l=()=>D,g=2);P(a,{name:c,fromWireType:k=>{for(var n=D[k>>2],m=l(),q,r=k+4,v=0;v<=n;++v){var w=k+4+v*b;if(v==n||0==m[w>>g])r=
d(r,w-r),void 0===q?q=r:(q+=String.fromCharCode(0),q+=r),r=w+b}W(k);return q},toWireType:(k,n)=>{if("string"!=typeof n)throw new N(`Cannot pass non-string to C++ string type ${c}`);var m=f(n),q=Zb(4+m+b);D[q>>2]=m>>g;e(n,q+4,m+b);null!==k&&k.push(W,q);return q},argPackAdvance:8,readValueFromPointer:yb,X(k){W(k)}})},z:(a,b)=>{b=I(b);P(a,{wa:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},s:(a,b,c,d,e)=>{a=Nb[a];b=xb(b);c=Mb(c);var f=[];D[d>>2]=eb(f);return a(b,c,f,e)},t:(a,b,c,
d)=>{a=Nb[a];b=xb(b);c=Mb(c);a(b,c,null,d)},g:wb,l:(a,b)=>{var c=Qb(a,b),d=c[0];b=d.name+"_$"+c.slice(1).map(function(m){return m.name}).join("_")+"$";var e=Rb[b];if(void 0!==e)return e;e=["retType"];for(var f=[d],l="",g=0;g<a-1;++g)l+=(0!==g?", ":"")+"arg"+g,e.push("argType"+g),f.push(c[1+g]);var k="return function "+Wa("methodCaller_"+b)+"(handle, name, destructors, args) {\n",n=0;for(g=0;g<a-1;++g)k+="    var arg"+g+" = argType"+g+".readValueFromPointer(args"+(n?"+"+n:"")+");\n",n+=c[g+1].argPackAdvance;
k+="    var rv = handle[name]("+l+");\n";for(g=0;g<a-1;++g)c[g+1].deleteObject&&(k+="    argType"+g+".deleteObject(arg"+g+");\n");d.wa||(k+="    return retType.toWireType(destructors, rv);\n");e.push(k+"};\n");a=sb(e).apply(null,f);e=Ob(a);return Rb[b]=e},q:a=>{4<a&&(Y.get(a).pa+=1)},A:a=>{var b=xb(a);rb(b);wb(a)},r:(a,b)=>{a=Pb(a,"_emval_take_value");a=a.readValueFromPointer(b);return eb(a)},m:()=>{la("")},w:(a,b,c)=>y.copyWithin(a,b,b+c),v:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=
1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-ma.buffer.byteLength+65535)/65536;try{ma.grow(e);sa();var f=1;break a}catch(l){}f=void 0}if(f)return!0}return!1},n:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var l=D[b>>2],g=D[b+4>>2];b+=8;for(var k=0;k<g;k++){var n=y[l+k],m=Sb[a];0===n||10===n?((1===a?ka:u)(H(m,0)),m.length=0):m.push(n)}e+=g}D[d>>2]=e;return 0}},Z=function(){function a(c){Z=c.exports;ma=Z.B;sa();kb=
Z.G;ua.unshift(Z.C);E--;h.monitorRunDependencies&&h.monitorRunDependencies(E);0==E&&(null!==xa&&(clearInterval(xa),xa=null),F&&(c=F,F=null,c()));return Z}var b={a:$b};E++;h.monitorRunDependencies&&h.monitorRunDependencies(E);if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){u(`Module.instantiateWasm callback failed with error: ${c}`),ca(c)}Da(b,function(c){a(c.instance)}).catch(ca);return{}}(),W=h._free=a=>(W=h._free=Z.D)(a),Zb=h._malloc=a=>(Zb=h._malloc=Z.E)(a);
h._generate_path_map=(a,b,c,d,e,f)=>(h._generate_path_map=Z.F)(a,b,c,d,e,f);var ob=a=>(ob=Z.H)(a);h.__embind_initialize_bindings=()=>(h.__embind_initialize_bindings=Z.I)();var Ub=()=>(Ub=Z.J)(),Vb=a=>(Vb=Z.K)(a),Tb=a=>(Tb=Z.L)(a);h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=Z.N)(a,b,c,d,e);h.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?h["_"+a]:function(){return Wb(a,b,c,arguments)}};var ac;F=function bc(){ac||cc();ac||(F=bc)};
function cc(){function a(){if(!ac&&(ac=!0,h.calledRun=!0,!na)){Ea(ua);ba(h);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();va.unshift(b)}Ea(va)}}if(!(0<E)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)wa();Ea(ta);0<E||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();cc();


  return moduleArg.ready
}

);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = create_noita_random;
else if (typeof define === 'function' && define['amd'])
  define([], () => create_noita_random);
